CREATE TABLE IF NOT EXISTS `homepage_sections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`slug` varchar(128) NOT NULL,
	`section_type` enum('hero','trending','headlines','category','in_brief','podcasts','videos','stocks','sidebar_jobs','sidebar_events','sidebar_links','sidebar_podcast') DEFAULT 'category',
	`category_id` int,
	`accent_color` varchar(7) DEFAULT '#000000',
	`icon` varchar(64),
	`article_count` int DEFAULT 4,
	`layout` enum('featured_grid','two_column','list','horizontal_scroll','compact') DEFAULT 'featured_grid',
	`show_image` boolean DEFAULT true,
	`show_excerpt` boolean DEFAULT true,
	`show_date` boolean DEFAULT true,
	`show_author` boolean DEFAULT false,
	`show_view_more` boolean DEFAULT true,
	`view_more_url` text,
	`sort_order` int DEFAULT 0,
	`is_active` boolean DEFAULT true,
	`position` enum('main','sidebar') DEFAULT 'main',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `homepage_sections_id` PRIMARY KEY(`id`),
	CONSTRAINT `homepage_sections_slug_unique` UNIQUE(`slug`)
);
