/**
 * TechScoop SEO Edge Worker
 * ----------------------------------------------------------------------
 * Goal: stop the Manus platform CDN from intercepting /sitemap*.xml and
 *       /robots.txt with the SPA "Article Not Found" fallback.
 *
 * Cloudflare runs in front of Manus. This Worker:
 *   1. Catches every request for an SEO file at the apex path.
 *   2. Internally rewrites it to the /api/ counterpart on origin (which the
 *      Manus edge does NOT intercept — confirmed in server/_core/index.ts).
 *   3. Falls back to the static asset on origin if /api/ returns 5xx.
 *   4. Forces Content-Type, kills Manus's noindex header, and pins
 *      Cache-Control so Google doesn't see a 90-day stale copy.
 *
 * Deployment:
 *   - Wrangler:   `wrangler deploy cloudflare/seo-worker.js`
 *   - Route:      techscoop.io/sitemap*.xml, techscoop.io/robots.txt,
 *                 techscoop.io/sitemap.xml, techscoop.io/rss.xml,
 *                 techscoop.io/feed.xml, techscoop.io/jobs-feed.xml
 *   - Compatibility date: 2025-01-01 or later.
 *
 * Wrangler config (cloudflare/wrangler.toml) is committed alongside.
 */

const SEO_PATHS = new Set([
  "/sitemap.xml",
  "/sitemap-index.xml",
  "/sitemap-articles.xml",
  "/sitemap-news.xml",
  "/sitemap-jobs.xml",
  "/sitemap-people.xml",
  "/sitemap-investors.xml",
  "/sitemap-companies.xml",
  "/sitemap-accelerators.xml",
  "/sitemap-events.xml",
  "/sitemap-resources.xml",
  "/sitemap-research.xml",
  "/sitemap-categories.xml",
  "/sitemap-tags.xml",
  "/sitemap-authors.xml",
  "/sitemap-images.xml",
  "/sitemap-pages.xml",
  "/robots.txt",
  "/rss.xml",
  "/feed.xml",
  "/jobs-feed.xml",
  "/ads.txt",
]);

const XML_PATH = /^\/sitemap[\w-]*\.xml$/;

function contentTypeFor(pathname) {
  if (pathname.endsWith(".xml")) return "application/xml; charset=utf-8";
  if (pathname.endsWith(".txt")) return "text/plain; charset=utf-8";
  return "application/octet-stream";
}

async function fetchOrigin(url, init) {
  // Cloudflare-native fetch hits origin directly. We disable the "Apps" cache
  // here so each request re-validates with the Express dynamic route — the
  // origin response itself sets a 1-hour Cache-Control which CF respects.
  return fetch(url, {
    ...init,
    cf: {
      cacheEverything: false,
      cacheTtl: 0,
    },
  });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const pathname = url.pathname;

    // Pass through everything that isn't an SEO file
    if (!SEO_PATHS.has(pathname) && !XML_PATH.test(pathname)) {
      return fetch(request);
    }

    // 1. Try /api/<file> on origin (Express dynamic route)
    const apiUrl = new URL(url);
    apiUrl.pathname = "/api" + pathname;
    let resp;
    try {
      resp = await fetchOrigin(apiUrl.toString(), {
        method: "GET",
        headers: { "user-agent": request.headers.get("user-agent") || "Cloudflare-Worker/seo" },
        redirect: "follow",
      });
    } catch (err) {
      resp = null;
    }

    // 2. Fallback: hit origin static asset directly (pre-generated by
    //    scripts/generate-sitemaps.ts during build). Any error status
    //    falls back — a 404 from /api/ (route not mounted on this
    //    origin) must not short-circuit into the empty-sitemap guard.
    if (!resp || resp.status >= 400) {
      try {
        resp = await fetchOrigin(url.toString(), {
          method: "GET",
          headers: { "user-agent": request.headers.get("user-agent") || "Cloudflare-Worker/seo-static" },
          redirect: "follow",
        });
      } catch (_err) {
        return new Response("SEO file unavailable", { status: 503 });
      }
    }

    // 3. Reject HTML — that means the Manus fallback leaked through
    const ct = (resp.headers.get("content-type") || "").toLowerCase();
    if (ct.includes("text/html")) {
      return new Response(
        pathname.endsWith(".txt")
          ? "User-agent: *\nAllow: /\n"
          : '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>',
        {
          status: 200,
          headers: {
            "content-type": contentTypeFor(pathname),
            "cache-control": "public, max-age=300",
            "x-seo-worker": "html-leak-blocked",
          },
        }
      );
    }

    // 4. Re-emit with hardened headers
    const headers = new Headers(resp.headers);
    headers.set("content-type", contentTypeFor(pathname));
    headers.set("cache-control", "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400");
    headers.set("x-content-type-options", "nosniff");
    // Strip any Manus-injected noindex
    headers.delete("x-robots-tag");
    headers.set("x-robots-tag", "noarchive");
    // Diagnostic marker
    headers.set("x-seo-worker", "v1");

    return new Response(resp.body, {
      status: resp.status,
      headers,
    });
  },
};
