/**
 * The site's own words.
 *
 * Everything a reader sees that is not article copy: navigation, buttons,
 * labels, the footer. Translating 268 articles and leaving "Share:" and
 * "Read more" in English produces a page that is Arabic in the middle and
 * English around the edges, which reads worse than either.
 *
 * The English here is the source of truth and the fallback. A locale
 * translates as much of it as it has, key by key, and anything untranslated
 * shows in English rather than showing a key.
 *
 * Keys are dotted and grouped by where the string appears, so a translator
 * working down the list moves through the page rather than through the
 * codebase.
 */

export const UI_STRINGS = {
  // -------------------------------------------------------------- header
  "nav.search": "Search",
  "nav.searchPlaceholder": "Search {site}",
  "nav.signIn": "Sign in",
  "nav.signOut": "Sign out",
  "nav.account": "Account",
  "nav.createAccount": "Create account",
  "nav.profile": "Profile",
  "nav.dashboard": "Dashboard",
  "nav.myContent": "My content",
  "nav.menu": "Menu",
  "nav.close": "Close",
  "nav.language": "Language",
  "nav.readThisPageIn": "Read this page in",
  "nav.edition": "Edition",
  "nav.chooseEdition": "Choose edition",

  // ------------------------------------------------------------- article
  "article.topics": "Topics",
  "article.share": "Share",
  "article.shareThisArticle": "Share this article",
  "article.save": "Save",
  "article.saved": "Saved",
  "article.viewBio": "View bio",
  "article.by": "By",
  "article.published": "Published",
  "article.updated": "Updated",
  "article.minRead": "{n} min read",
  "article.relatedReading": "Related reading",
  "article.moreFrom": "More from {category}",
  "article.followThisStory": "Follow this story",
  "article.readMore": "Read more",
  "article.inThisArticle": "In this article",
  "article.companies": "Companies",
  "article.people": "People",
  "article.source": "Source",
  "article.correction": "Corrections",

  // -------------------------------------------------------------- lists
  "list.latest": "Latest",
  "list.topStory": "Top story",
  "list.sidebar": "Sidebar",
  "common.advertisement": "Advertisement",
  "common.viewAll": "View all",
  "common.all": "All",
  "common.subscribing": "Subscribing…",
  "common.supportJournalism": "Support independent journalism",
  "common.adBlocker": "Consider disabling your ad blocker for {site}",
  "newsletter.unsubscribeAnytime": "You can unsubscribe at any time. Read our",
  "search.placeholder": "Search articles, jobs, companies, people, events…",
  "search.noResults": "Try different keywords, or browse the categories",
  "search.quickLinks": "Quick links",
  "common.closeAd": "Close ad",
  "list.latestNews": "Latest News",
  "list.featuredCompanies": "Featured Companies",
  "list.featured": "Featured",
  "list.trending": "Trending",
  "list.mostRead": "Most read",
  "list.editorPicks": "Editor's picks",
  "list.loadMore": "Load more",
  "list.showingOf": "Showing {shown} of {total}",
  "list.noResults": "Nothing here yet",
  "list.page": "Page",
  "list.next": "Next",
  "list.previous": "Previous",

  // --------------------------------------------------------- newsletter
  "newsletter.subscribe": "Subscribe",
  "newsletter.emailPlaceholder": "Your email address",
  "newsletter.thanks": "You're subscribed.",
  "newsletter.error": "That didn't go through. Try again.",
  "newsletter.enterEmail": "Enter your email",
  "newsletter.stayUpdated": "Stay updated",
  "newsletter.confirmInbox": "Thanks for subscribing. Check your inbox to confirm.",
  "newsletter.confirmEmail": "Subscribed. Check your email to confirm.",
  "newsletter.needEmail": "Please enter your email address",
  "newsletter.selectLists": "Choose newsletters",
  "newsletter.consent": "By subscribing, you agree to our Privacy Policy.",
  "newsletter.dailyDescription": "The industrial stories that matter, every morning",
  "newsletter.projectsWeekly": "Projects Weekly",
  "newsletter.projectsDescription": "Major project awards and tenders",
  "newsletter.jobAlerts": "Job Alerts",
  "newsletter.jobsDescription": "New roles across the industry",
  "newsletter.eventUpdates": "Event Updates",
  "newsletter.eventsDescription": "Industry events coming up",

  // ------------------------------------------------------------- footer
  "footer.sections": "Sections",
  "footer.company": "Company",
  "footer.about": "About",
  "footer.contact": "Contact",
  "footer.advertise": "Advertise",
  "footer.privacy": "Privacy policy",
  "footer.terms": "Terms of use",
  "footer.rss": "RSS",
  "footer.allRightsReserved": "All rights reserved",
  "footer.followUs": "Follow us",


  // ------------------------------------------------- primary navigation
  // The header and footer link labels. These were hardcoded English arrays
  // until the archive went bilingual, which is why an Arabic page still had
  // an English masthead and an English footer under a translated article.
  "nav.news": "News",
  "nav.latest": "Latest",
  "nav.companies": "Companies",
  "nav.people": "People",
  "nav.events": "Events",
  "nav.jobs": "Jobs",
  "nav.newsletter": "Newsletter",
  "nav.directory": "Directory",
  "nav.industry": "Industry",
  "nav.explore": "Explore",
  "nav.me": "Me",

  // --------------------------------------------------------- categories
  // The industrial taxonomy, as it appears in navigation and on category
  // pages. Category names in the database stay English; these are what a
  // reader sees.
  "cat.construction": "Construction",
  "cat.infrastructure": "Infrastructure",
  "cat.energy": "Energy",
  "cat.manufacturing": "Manufacturing",
  "cat.logistics": "Logistics",
  "cat.real-estate": "Real Estate",
  "cat.transportation": "Transportation",
  "cat.industrial-technology": "Industrial Technology",
  "cat.mining": "Mining",
  "cat.utilities": "Utilities",

  // -------------------------------------------------------- footer links
  "footer.categories": "Categories",
  "footer.editorial": "Editorial",
  "footer.publication": "Publication",
  "footer.aboutUs": "About",
  "footer.contactUs": "Contact Us",
  "footer.termsOfService": "Terms of Service",
  "footer.privacyPolicy": "Privacy Policy",
  "footer.sitemap": "Sitemap",
  "footer.email": "Email",

  // -------------------------------------------------------------- state
  "state.loading": "Loading…",
  "state.error": "Something went wrong.",
  "state.retry": "Try again",
  "state.notFound": "Page not found",
  "state.notFoundBody": "The page you asked for does not exist or has moved.",
  "state.backHome": "Back to the front page",

  // ------------------------------------------------------------ generic
  "common.readingIn": "Reading in {language}",
  "common.translated": "Translated",
  "common.originalEnglish": "Read the original in English",

  // ------------------------------------- directories, filters, events
  // Everything the public pages beyond the homepage put around the
  // content: empty states, filter controls, directory headings, and the
  // events surface, which had the most English of any page.
  "article.companiesInArticle": "Companies in this article",
  "article.mentionedIn": "Mentioned in this article",
  "article.relatedArticles": "Related articles",
  "common.adSpace": "Ad space",
  "common.articles": "Articles",
  "common.cities": "Cities",
  "common.follow": "Follow",
  "common.showLess": "Show less",
  "common.showMore": "Show more",
  "common.viewDetails": "View details",
  "company.keyPeople": "Key people",
  "company.recentNews": "Recent news",
  "company.website": "Website",
  "directory.companies": "Company directory",
  "directory.companiesSubtitle": "The companies building the region",
  "directory.people": "People directory",
  "directory.peopleSubtitle": "Executives, engineers and leaders",
  "directory.peopleTagline": "The people running the region's industry",
  "directory.searchCompanies": "Search companies…",
  "directory.searchPeople": "Search people…",
  "events.connectPeople": "Connect people.",
  "events.coverage": "Event coverage",
  "events.discover": "Discover events.",
  "events.getTickets": "Get tickets",
  "events.happeningNow": "Happening right now",
  "events.hosting": "Hosting an event?",
  "events.listed": "Events listed",
  "events.liveNow": "Live now",
  "events.mostAnticipated": "Most anticipated",
  "events.pastPrompt": "Looking for something that already happened?",
  "events.search": "Search events",
  "events.searchLong": "Search events, topics or locations",
  "events.shapeThe": "Shape the",
  "events.submit": "Submit an event",
  "events.submitYours": "Submit your event",
  "events.tagline": "Every conference, summit and demo day that matters.",
  "events.type": "Event type",
  "events.view": "View event",
  "events.viewAll": "View all events",
  "events.viewPast": "View past events",
  "events.watchLive": "Watch live",
  "filter.allSectors": "All sectors",
  "filter.anyCity": "Any city",
  "filter.bySector": "Filter by sector",
  "filter.clear": "Clear",
  "filter.clearAll": "Clear all filters",
  "filter.clearFilters": "Clear filters",
  "list.browseCategories": "Browse categories",
  "list.browseTags": "Browse tags",
  "list.moreFromNewsroom": "More from the newsroom",
  "list.popularTags": "Popular tags",
  "list.showing": "Showing",
  "list.spotlight": "Spotlight",
  "state.articleNotFound": "Article not found",
  "state.authorNotFound": "Author not found",
  "state.backToNews": "Back to news",
  "state.categoryNotFound": "Category not found",
  "state.errorCompanies": "Could not load companies",
  "state.movedOrDeleted": "It may have been moved or deleted.",
  "state.noArticlesCategory": "No articles in this category yet.",
  "state.noArticlesTag": "No articles with this tag yet.",
  "state.noArticlesYet": "No articles published yet.",
  "state.noCities": "No cities found.",
  "state.noCompanies": "No companies found",
  "state.noPeople": "No people found",
  "state.noResults": "No results found",
  "state.noUpcomingEvents": "No upcoming events on the calendar yet",
  "state.noUpcomingEventsShort": "No upcoming events scheduled yet.",
  "state.tagNotFound": "Tag not found",
  "state.tryAdjusting": "Try adjusting your search or filters",

  // ------------------------------- the rest of the public site
  // Company and person profiles, jobs, events, the static pages and
  // the auth screens. Added in one pass after eight translators each
  // converted a batch of components.

  // --- about
  "about.accuracy": "Accuracy",
  "about.accuracyBody": "We verify reporting before publication, and contract values, project scopes and timelines are checked against primary sources wherever possible. When we get something wrong, we correct it promptly and say so — accuracy is the basis of any claim to be a publication of record.",
  "about.advertiseWithUs": "Advertise With Us",
  "about.anonymousSources": "Use of Anonymous Sources",
  "about.anonymousSources1": "We prefer named, on-the-record sources. We will grant anonymity only when (a) the information is materially in the public interest, (b) the source has direct knowledge, and (c) the source would face professional or personal harm by being named.",
  "about.anonymousSources2": "When we use an anonymous source, the reporter and at least one editor verify the source's identity and assess their motivation. We describe the source's relationship to the story with as much specificity as anonymity allows.",
  "about.contactForm": "contact form",
  "about.correctionsBody": "We correct factual errors promptly and transparently. When a story is updated to fix a mistake, we add a clearly labelled correction note at the bottom of the article describing what was wrong and what we changed. Substantive corrections are also flagged at the top of the story.",
  "about.correctionsPolicy": "Corrections Policy",
  "about.correctionsResponse": "We aim to respond to all correction requests within one business day.",
  "about.cover1": "We report on contract awards, tenders and project milestones across construction and infrastructure; upstream, midstream and downstream developments in oil & gas; power generation, transmission and renewables; and the manufacturing, logistics, transportation and mining activity that underpins regional economies. We also track the real estate developments, data centers and industrial technology reshaping how these sectors operate.",
  "about.cover2": "Alongside daily news, we maintain structured coverage of the companies active in these markets — contractors, developers, operators, suppliers and financiers — and the executives and engineers who lead them. Our project coverage follows major programs from announcement through award, construction and delivery.",
  "about.cover3": "We round this out with listings of industry events and conferences across the region, and job openings from the sectors we cover — so that {site} serves as a working reference for the industry, not just a news feed.",
  "about.depth": "Depth",
  "about.depthBody": "We do not just report what happened — we explain what it means for the market. Our readers are professionals who deserve context: how a contract fits a program, how a policy changes a sector's economics, how an appointment signals a company's direction.",
  "about.diversity": "Diversity & Representation",
  "about.diversity1": "The industrial economy is built by people from every country, background, and discipline. Our reporting aims to reflect that — in the sources we quote, the leaders we profile, and the stories we pursue beyond the region's largest hubs and best-known companies.",
  "about.diversity2": "Our editorial hiring is open to qualified candidates regardless of nationality, gender, religion, or background.",
  "about.editorialIntro": "These are the standards every member of the {site} editorial team is expected to uphold. They govern how we source, verify, write, and correct every story we publish.",
  "about.editorialPolicy": "Editorial Policy & Ethics",
  "about.events1": "{site} maintains a calendar of the conferences, exhibitions and industry gatherings that matter to the sectors we cover — from energy and construction summits in Riyadh and the GCC to logistics, mining and manufacturing events across MENA and beyond.",
  "about.events2": "Where our team attends or covers an event, that coverage follows the same editorial standards as the rest of the publication. Event organizers can reach us via the",
  "about.factChecking": "Verification & Fact-Checking",
  "about.factChecking1": "Every story published on {site} is checked against primary sources before it goes live. For contract awards and project announcements we rely on official statements, tender documents, regulatory filings or confirmation from the parties involved. For market data we cite the original report. For quotes we retain the original audio or written record.",
  "about.factChecking2": "Senior editors review investigative pieces and any story that names individuals in a critical context. Where a claim cannot be verified to our standard, we either delay publication, attribute it to a single named source, or omit it.",
  "about.fairness": "Fairness",
  "about.fairnessBody": "We give the subjects of our reporting a fair opportunity to respond. We present multiple perspectives on contested issues, distinguish clearly between news and analysis, and apply the same standard of rigor to every company we cover, regardless of its size or commercial relationship with us.",
  "about.getInTouch": "Get in Touch",
  "about.getInTouchBody": "Have a story tip, a correction, a partnership inquiry, or feedback about our coverage? Visit our contact page or reach out directly by email.",
  "about.independence": "Independence",
  "about.independenceBody": "Editorial decisions are made independently of our business relationships. Advertising and sponsorship never determine what we cover or how we cover it. Sponsored and branded content is always clearly labelled and produced separately from news coverage.",
  "about.intro1": "{site} covers the physical economy — the industries that design, build, power, move and maintain the world around us. Our reporting spans construction, infrastructure, energy, oil & gas, utilities, manufacturing, logistics, transportation, aviation, ports, rail, mining, metals, chemicals, real estate development, data centers and industrial technology.",
  "about.intro2": "Our coverage starts in Saudi Arabia, extends across the GCC and the wider MENA region, and follows the projects, companies and capital flows that connect those markets to the rest of the world. That priority order — Saudi Arabia, then the GCC, then MENA, then global — shapes what we cover first and in what depth.",
  "about.intro3": "{site} is written for the people who work in these industries: contractors, developers, engineers, operators, procurement teams, financiers and policymakers. We assume our readers know their sectors, and we aim to tell them something they can use.",
  "about.mission": "Our Mission",
  "about.mission1": "The industrial economy is reported in fragments — a contract award here, an executive appointment there, a project milestone buried in a quarterly filing. {site} exists to bring that reporting together into structured, connected coverage: news, the companies behind it, the people who lead them, the projects they deliver, the events where the industry meets, and the jobs it creates.",
  "about.mission2": "When we report on a project, we link it to the owners, contractors and consultants delivering it. When we cover an appointment, we connect it to the company's track record. The goal is a body of coverage that compounds — where each story adds context to the ones around it.",
  "about.mission3": "Our editorial decisions are driven by what matters to people working in these sectors, not by press-release volume or publicity cycles. We would rather publish one story that changes how a reader understands a market than ten that restate an announcement.",
  "about.orUseOur": "or use our",
  "about.ownership": "Ownership & Funding",
  "about.ownership1": "{site} is operated by {legalName}. The publication is funded by advertising, sponsorship, and partnership revenue. No advertiser, sponsor, or partner has any role in editorial decisions or pre-publication review of stories.",
  "about.ownership2": "When a story involves a company that is also a commercial partner of {site}, we disclose the relationship in the article.",
  "about.spottedError": "Spotted an error? Email",
  "about.title": "About {site}",
  "about.whatWeCover": "What We Cover",
  // --- advertise
  "advertise.adFormats": "Ad Formats",
  "advertise.adsSponsorships": "{site} Ads & Sponsorships",
  "advertise.allInquiriesSentTo": "All inquiries are sent to",
  "advertise.budget10to25k": "Yes, $10,000–$25,000",
  "advertise.budget25to50k": "Yes, $25,000–$50,000",
  "advertise.budget50kPlus": "Yes, $50,000+",
  "advertise.budgetNone": "No / I'm looking for editorial coverage",
  "advertise.budgetQuestion": "Do you have a marketing budget for this initiative?",
  "advertise.budgetUnder10k": "Yes, less than $10,000",
  "advertise.companyPlaceholder": "Your company",
  "advertise.contactPageLink": "contact page",
  "advertise.emailPlaceholder": "your@company.com",
  "advertise.formNote": "This form is for paid sponsorship and advertising inquiries only. For editorial pitches or press outreach, please see our",
  "advertise.inContent": "In-Content",
  "advertise.inContentDesc": "728×90 units placed within article bodies, seen at the point of reading.",
  "advertise.indChemicals": "Chemicals",
  "advertise.indConstruction": "Construction & Contracting",
  "advertise.indDataCenters": "Data Centers / Industrial Technology",
  "advertise.indEnergy": "Energy / Oil & Gas",
  "advertise.indEngineering": "Engineering / Professional Services",
  "advertise.indFinancial": "Financial Services",
  "advertise.indGovernment": "Government / Public Sector",
  "advertise.indLogistics": "Logistics / Supply Chain",
  "advertise.indMining": "Mining & Metals",
  "advertise.indRealEstate": "Real Estate Development",
  "advertise.indTransport": "Transportation / Aviation / Ports / Rail",
  "advertise.indUtilities": "Utilities & Power",
  "advertise.inquiryReceived": "Inquiry received",
  "advertise.inquiryReceivedBody": "Our media team will reach out within 1 business day.",
  "advertise.intro": "{site} is read by the people who plan, build, and operate the physical economy — contractors, developers, engineers, energy and utility executives, logistics operators, procurement leaders, and the financiers behind them — with coverage focused on Saudi Arabia, the GCC and MENA. Advertising with {site} puts your brand alongside the news these decision-makers rely on, in a professional editorial environment rather than a general-interest feed.",
  "advertise.leaderboard": "Leaderboard",
  "advertise.leaderboardDesc": "970×250 and 970×90 placements at the top of the homepage, section fronts, and articles.",
  "advertise.mediaKit": "For a media kit, current availability, and rates, email",
  "advertise.messageHint": "This is your opportunity to ask us for specifics to be addressed in our initial reply. Please keep this section short and to the point about your ask.",
  "advertise.messagePlaceholder": "Tell us about your advertising goals...",
  "advertise.mobile": "Mobile",
  "advertise.mobileDesc": "Mobile-optimized banner and sticky formats for readers on phones and tablets.",
  "advertise.native": "Native & Branded Content",
  "advertise.nativeDesc": "Clearly labelled sponsored articles and branded features, produced to editorial standards.",
  "advertise.newsletterSponsorship": "Newsletter Sponsorship",
  "advertise.newsletterSponsorshipDesc": "Dedicated placements in {name}, delivered to subscribers' inboxes every morning.",
  "advertise.objBranded": "Distribute branded content / sponsored article",
  "advertise.objDisplay": "Run display advertising on the site",
  "advertise.objNewsletter": "Sponsor the newsletter",
  "advertise.objOther": "Something else (please explain in the Message area)",
  "advertise.objPromote": "Promote an event, tender, or recruitment campaign",
  "advertise.objectives": "Advertising Objectives",
  "advertise.orUseForm": "or use the form below.",
  "advertise.rightRail": "Right Rail",
  "advertise.rightRailDesc": "300×250 and 300×600 units in the sidebar, persistent across article and listing pages.",
  "advertise.rolePlaceholder": "Your role",
  "advertise.submitFailed": "Couldn't submit your inquiry",
  "advertise.title": "Advertise with {site}",
  // --- article
  "article.readLess": "Read less",
  // --- assessment
  "assessment.anyLanguage": "any",
  "assessment.autoSave": "Answers auto-save as you move on.",
  "assessment.codePlaceholder": "// Write your solution here",
  "assessment.confirmSubmit": "Submit your assessment? You can't change answers after this.",
  "assessment.fileUploadUnsupported": "File upload questions aren't supported in this version. Skip this and we'll grade manually.",
  "assessment.language": "Language",
  "assessment.linkExpired": "The invite link may have expired or already been used.",
  "assessment.loading": "Loading your assessment…",
  "assessment.missingToken": "Missing invite token. Use the link from the email we sent you.",
  "assessment.points": "pts",
  "assessment.questionAbbrev": "Q",
  "assessment.questionOf": "Question {n} of {total}",
  "assessment.recorded": "Your assessment has been recorded. We'll let you know how you did via email.",
  "assessment.runCode": "Run my code against the test cases on save (slower)",
  "assessment.saveFailed": "Couldn't save answer",
  "assessment.submit": "Submit assessment",
  "assessment.submitted": "Submitted!",
  "assessment.suggestedSeconds": "{n}s suggested",
  "assessment.title": "Assessment",
  "assessment.typeCoding": "Coding",
  "assessment.typeFileUpload": "File upload",
  "assessment.typeLongAnswer": "Long answer",
  "assessment.typeMultipleChoice": "Multiple choice",
  "assessment.typeShortAnswer": "Short answer",
  "assessment.typeSystemDesign": "System design",
  "assessment.unavailable": "This assessment isn't available.",
  "assessment.yourAnswer": "Your answer",
  "assessment.yourAnswerLong": "Your answer — explain your thinking and trade-offs.",
  // --- auth
  "auth.agreeTo": "I agree to {site}'s",
  "auth.alreadyHaveAccount": "Already have an account?",
  "auth.backTo": "Back to {site}",
  "auth.benefitAlerts": "Custom News Alerts",
  "auth.benefitAlertsBody": "Receive breaking news about topics and companies you care about",
  "auth.benefitBoard": "Tech jobs board",
  "auth.benefitBoardBody": "apply with one click to roles at MENA-backed companies",
  "auth.benefitFeed": "Personalised feed",
  "auth.benefitFeedBody": "sectors, geographies, and funding stages you actually care about",
  "auth.benefitFounders": "Founder resources",
  "auth.benefitFoundersBody": "perks, playbooks, and templates from operators in the region",
  "auth.benefitMatches": "Personalized Job Matches",
  "auth.benefitMatchesBody": "Get matched with industry roles based on your skills and preferences",
  "auth.benefitResources": "Exclusive Resources",
  "auth.benefitResourcesBody": "Access founder perks, templates, playbooks, and calculators",
  "auth.benefitTracking": "Track Companies & Funding",
  "auth.benefitTrackingBody": "Follow companies and get notified about new projects and contract awards",
  "auth.bySigningIn": "By signing in you agree to our",
  "auth.choosePassword": "Please enter a password",
  "auth.confirmPassword": "Confirm Password",
  "auth.confirmPasswordPlaceholder": "Confirm your password",
  "auth.createFreeAccount": "Create a free account",
  "auth.createYourAccount": "Create Your Account",
  "auth.creatingAccount": "Creating Account...",
  "auth.ctaBody": "Get instant access to job matches, founder resources, and the latest news from the region's tech ecosystem.",
  "auth.ctaHeadline": "Ready to Join MENA's Tech Community?",
  "auth.email": "Email",
  "auth.emailAddress": "Email Address",
  "auth.enterEmail": "Please enter your email",
  "auth.enterName": "Please enter your name",
  "auth.enterPassword": "Please enter your password",
  "auth.forgotPassword": "Forgot password?",
  "auth.freeAndFast": "It's free and takes less than a minute",
  "auth.fullName": "Full Name",
  "auth.fullNamePlaceholder": "Enter your full name",
  "auth.genericError": "An error occurred. Please try again.",
  "auth.hidePassword": "Hide password",
  "auth.invalidCredentials": "Invalid email or password",
  "auth.invalidEmail": "Please enter a valid email address",
  "auth.joinBadge": "Join the region's industry professionals",
  "auth.keepSignedIn": "Keep me signed in for 30 days",
  "auth.membersSay": "What Our Members Say",
  "auth.mustAgree": "Please agree to the Terms of Service and Privacy Policy",
  "auth.nameTooShort": "Name must be at least 2 characters",
  "auth.newTo": "New to {site}?",
  "auth.noAccountSignUp": "Don't have an account? Sign up free",
  "auth.panelBody": "Independent reporting on the companies and projects building the region's technology future — Saudi Arabia, the UAE, Egypt, and beyond.",
  "auth.panelEyebrow": "MENA's tech ecosystem, in one feed",
  "auth.panelHeadline": "Funding rounds. Founders. Jobs.",
  "auth.password": "Password",
  "auth.passwordPlaceholder": "Create a password (min. 8 characters)",
  "auth.passwordTooShort": "Password must be at least 8 characters",
  "auth.passwordsMismatch": "Passwords do not match",
  "auth.registrationFailed": "Registration failed. Please try again.",
  "auth.showPassword": "Show password",
  "auth.signInRequired": "Sign in required",
  "auth.signinSubtitle": "Sign in to follow the region's industry, save articles, apply to jobs, and customise your news feed.",
  "auth.signingIn": "Signing in…",
  "auth.signupHeadline": "Your window on the region's industrial economy",
  "auth.signupSubhead": "Create your free account to access personalized job matches, exclusive founder resources, and stay ahead with curated news from the region's fastest-growing tech scene.",
  "auth.subscribeNewsletter": "Subscribe to {newsletter} (recommended)",
  "auth.testimonialOne": "{site} helped me land my dream job at an EPC contractor in Riyadh.",
  "auth.testimonialOneRole": "Product Manager",
  "auth.testimonialTwo": "The best resource for staying updated on the region's industrial economy.",
  "auth.testimonialTwoRole": "Founder & CEO",
  "auth.trustedBy": "Trusted by professionals at",
  "auth.welcomeBack": "Welcome back",
  // --- claim
  "claim.accountEmail": "Your Account Email",
  "claim.adminWillVerify": "An admin will review and verify your ownership before approving.",
  "claim.autoDetected": "Auto-detected from your account",
  "claim.charCount": "{n}/2000 characters",
  "claim.claim": "Claim",
  "claim.claimProfileTitle": "Claim {entity} Profile",
  "claim.claimThis": "Claim this {entity}",
  "claim.claimed": "Claimed",
  "claim.clarificationNeeded": "Clarification Needed",
  "claim.companyEmailHelp": "Providing a company email helps speed up verification",
  "claim.companyEmailLabel": "Company / Organization Email",
  "claim.entityAccelerator": "Accelerator",
  "claim.entityCompany": "Company",
  "claim.entityEvent": "Event",
  "claim.entityInvestor": "Investor",
  "claim.entityPerson": "Person",
  "claim.manage": "Manage",
  "claim.manageProfile": "Manage Profile",
  "claim.noEmailOnFile": "No email on file",
  "claim.pending": "Claim Pending",
  "claim.proofLabel": "Proof of Ownership",
  "claim.proofPlaceholder": "Provide any proof: LinkedIn profile URL, company website link, official document reference, etc.",
  "claim.reasonLabel": "Reason for Claiming",
  "claim.reasonPlaceholder": "e.g. I am the founder/CEO of this company, I am the person listed, I represent this organization...",
  "claim.reasonRequired": "Please provide a reason for your claim",
  "claim.rejected": "Claim Rejected",
  "claim.submit": "Submit Claim",
  "claim.submitFailed": "Failed to submit claim request",
  "claim.submitRequestFor": "Submit a claim request for",
  "claim.submitted": "Claim request submitted! An admin will review your request.",
  "claim.underReview": "Under Review",
  "claim.whatNext": "What happens next?",
  "claim.whatNextBody": "After submitting, an admin will review your request. You may be asked for additional clarification. Once approved, you will be able to manage this profile, post content, and manage job listings.",
  // --- common
  "common.and": "and",
  "common.apply": "Apply",
  "common.at": "at",
  "common.breadcrumb": "Breadcrumb",
  "common.cancel": "Cancel",
  "common.city": "City",
  "common.dismiss": "Dismiss",
  "common.done": "Done",
  "common.following": "Following",
  "common.high": "High",
  "common.lastUpdated": "Last updated",
  "common.linkCopied": "Link Copied",
  "common.low": "Low",
  "common.medium": "Medium",
  "common.message": "Message",
  "common.notAvailable": "N/A",
  "common.optional": "Optional",
  "common.optionalSuffix": "(optional)",
  "common.other": "Other",
  "common.saving": "Saving…",
  "common.select": "Select...",
  "common.submitting": "Submitting...",
  "common.unknown": "Unknown",
  "common.uploading": "Uploading...",
  "common.view": "View",
  "common.yourEmail": "Your Email",
  // --- company
  "company.aboutName": "About {name}",
  "company.awards": "Awards & Recognition",
  "company.boilerplate": "Company Boilerplate",
  "company.caseStudies": "Case Studies",
  "company.certifications": "Certifications",
  "company.claimPrompt": "Claim this profile to update information, post jobs, and track analytics.",
  "company.clientLabel": "Client: {name}",
  "company.clients": "Clients",
  "company.connect": "Connect",
  "company.contact": "Contact",
  "company.contactDescription": "Send a message to this company. They will receive it via email.",
  "company.contactTitle": "Contact {name}",
  "company.countries": "Countries",
  "company.coverAlt": "{name} cover",
  "company.dataSource": "Data source",
  "company.dataTransparency": "Data Transparency",
  "company.details": "Company Details",
  "company.employees": "Employees",
  "company.established": "Est. {year}",
  "company.focusAreas": "Focus Areas",
  "company.founded": "Founded",
  "company.funding": "Funding",
  "company.headquarters": "Headquarters",
  "company.hiring": "Hiring",
  "company.industry": "Industry",
  "company.isThisYours": "Is this your company?",
  "company.keyMetrics": "Key Metrics",
  "company.lastUpdated": "Last updated",
  "company.leadership": "Leadership Team",
  "company.linkCopied": "Profile link copied to clipboard!",
  "company.logoPack": "Logo Pack",
  "company.marketServed": "Market Served",
  "company.mediaKit": "Media Kit",
  "company.messagePlaceholder": "Write your message...",
  "company.messageSent": "Message sent!",
  "company.messageSentBody": "The company will be notified.",
  "company.mission": "Mission",
  "company.nEmployees": "{n} employees",
  "company.newsCoverage": "News & Media Coverage",
  "company.noDescription": "No description available.",
  "company.noJobs": "No open positions",
  "company.noJobsBody": "{name} doesn't have any open positions right now.",
  "company.noNews": "No news coverage yet",
  "company.noNewsBody": "Articles mentioning {name} will appear here.",
  "company.noPress": "No press materials available yet.",
  "company.noProducts": "No products listed",
  "company.noProductsBody": "Product information for {name} hasn't been added yet.",
  "company.noTeam": "No team members listed",
  "company.noTeamBody": "Team information for {name} hasn't been added yet.",
  "company.notableCustomers": "Notable Customers",
  "company.nowFollowing": "Following {name}",
  "company.openPositions": "Open Positions ({n})",
  "company.partnerships": "Strategic Partnerships",
  "company.prContact": "PR Contact",
  "company.pressPr": "Press & PR",
  "company.problemSolved": "Problem Solved",
  "company.profile": "Company Profile",
  "company.profileMeta": "{name} company profile on {site}.",
  "company.profileStrength": "Profile Strength",
  "company.profileViews": "Profile Views",
  "company.recentUpdates": "Recent Updates",
  "company.regions": "Regions",
  "company.resources": "Resources",
  "company.screenshotAlt": "{name} screenshot {n}",
  "company.sectors": "Sectors",
  "company.sendMessage": "Send Message",
  "company.shareProfile": "Share Profile",
  "company.signInToFollow": "Please sign in to follow companies.",
  "company.similar": "Similar Companies",
  "company.similarHiring": "Similar Companies Hiring",
  "company.stage": "Stage",
  "company.strengthHigh": "Featured ready",
  "company.strengthLow": "Basic — add more info to rank higher",
  "company.strengthMedium": "Discoverable",
  "company.tabOverview": "Overview",
  "company.tabPress": "Press & Resources",
  "company.tabProducts": "Products",
  "company.teamOn": "Team Members on {site}",
  "company.teamSize": "Team Size",
  "company.techStack": "Tech Stack",
  "company.timeline": "Company Timeline",
  "company.unfollowed": "Unfollowed {name}",
  "company.verification": "Verification",
  "company.verified": "Verified",
  "company.viewCompanyProfile": "View Company Profile",
  "company.viewProfile": "View Profile",
  "company.vision": "Vision",
  "company.visitWebsite": "Visit website",
  "company.watchDemo": "Watch Demo",
  "company.whitepapers": "Whitepapers",
  // --- contact
  "contact.advertising": "Advertising & Sponsorships",
  "contact.advertisingBody": "For advertising and sponsorship inquiries, please",
  "contact.advertisingLink": "visit our advertise page",
  "contact.advertisingSuffix": "and our media team will get back to you quickly.",
  "contact.companyPlaceholder": "Your company or organization",
  "contact.corrections": "Corrections & Feedback",
  "contact.correctionsBody": "We take accuracy seriously. If you've spotted an error in our reporting or have feedback about our coverage, please reach out to",
  "contact.emailPlaceholder": "your@email.com",
  "contact.enquiryAbout": "What is your enquiry about?",
  "contact.eventsListings": "Events & Listings",
  "contact.eventsListingsBody": "Organizing an industry event, or want a role or event listed on the site? Please contact",
  "contact.intro": "Whether you have a news tip, want to work with us, or just have a question — we're here to help. Choose the most relevant category below or use the general inquiry form.",
  "contact.messagePlaceholder": "Tell us more about your inquiry...",
  "contact.messageSent": "Message sent",
  "contact.messageSentBody": "We've received your message and will reply within 1 business day.",
  "contact.newsTips": "News Tips",
  "contact.newsTipsBody": "Know about a contract award, project development, or industry move we should be covering? We'd love to hear from you. Please drop us a note at",
  "contact.newsTipsNote": "If you prefer to remain anonymous, please mention that in your email and we will protect your identity.",
  "contact.otherInquiries": "Other Inquiries",
  "contact.otherInquiriesBody": "For anything else, fill out the form below and we'll route your message to the right team. All inquiries are sent to",
  "contact.partnership": "Partnership Inquiry",
  "contact.pressReleases": "Press Releases & Announcements",
  "contact.pressReleasesBody": "Announcing a contract win, project milestone, executive appointment, or product for the industrial sector? Send your release to",
  "contact.pressReleasesNote": "Please include the key facts — parties involved, scope, value if disclosed, and timeline — plus any supporting materials.",
  "contact.sendFailed": "Couldn't send your message",
  "contact.workEmailNote": "If you're able, we prefer to connect through your work email.",
  // --- cookies
  "cookies.acceptAll": "Accept all",
  "cookies.analytics": "Analytics",
  "cookies.analyticsHelp": "Help us understand how visitors use the site so we can improve it.",
  "cookies.body": "We use cookies to make {site} work and to understand how you use it. Read our",
  "cookies.closePanel": "Close customize panel",
  "cookies.consent": "Cookie consent",
  "cookies.customize": "Customize",
  "cookies.essential": "Essential",
  "cookies.essentialHelp": "Required for the site to function (authentication, security, preferences).",
  "cookies.marketing": "Marketing",
  "cookies.marketingHelp": "Used to deliver relevant ads and measure campaign performance.",
  "cookies.preferences": "Cookie preferences",
  "cookies.preferencesHelp": "Choose which categories of cookies you allow. Essential cookies are always on.",
  "cookies.rejectAll": "Reject all",
  "cookies.savePreferences": "Save preferences",
  "cookies.title": "We value your privacy",
  // --- dashboard
  "dashboard.allMatches": "All your matches",
  "dashboard.applyWithProfile": "Apply with your profile",
  "dashboard.completeProfile": "Complete your profile to get better matches. You're {percent}% there!",
  "dashboard.goToProfile": "Go to profile",
  "dashboard.highSalary": "High salary roles",
  "dashboard.newJobsThisWeek": "New jobs this week",
  "dashboard.personalizedForYou": "Personalized for you",
  "dashboard.recentlyFunded": "Recently funded companies",
  "dashboard.recommendedCompanies": "Recommended companies",
  "dashboard.remoteJobs": "Remote jobs",
  "dashboard.topPicks": "Top picks for you",
  "dashboard.welcomeBackNamed": "Welcome back, {name}",
  "dashboard.yourMatches": "Your matches",
  // --- dept
  "dept.businessDevelopment": "Business Development",
  "dept.customerSuccess": "Customer Success",
  "dept.data": "Data",
  "dept.design": "Design",
  "dept.engineering": "Engineering",
  "dept.finance": "Finance",
  "dept.humanResource": "Human Resource",
  "dept.legal": "Legal",
  "dept.marketing": "Marketing",
  "dept.operations": "Operations",
  "dept.product": "Product",
  "dept.sales": "Sales",
  "dept.technology": "Technology",
  // --- edition
  "edition.currentlyViewing": "Currently viewing: {edition} edition",
  "edition.firstVisitNote": "You're viewing the {edition} edition. Content from your country surfaces first. Switch via the flag in the header.",
  // --- event
  "event.addressPlaceholder": "Street, district",
  "event.browseAllEvents": "Browse all events",
  "event.buyTickets": "Buy tickets",
  "event.byInterestOn": "Upcoming events by interest on {site}",
  "event.byTheNumbers": "By the numbers",
  "event.cityPlaceholder": "Riyadh",
  "event.descriptionHint": "What's the event about? Who should attend? ({count} / 5000)",
  "event.descriptionPlaceholder": "A few sentences explaining the agenda, audience, and what attendees will get.",
  "event.errDescriptionLength": "Description must be 5000 characters or fewer.",
  "event.errFixFields": "Please fix the highlighted fields and try again.",
  "event.errFullUrl": "Enter a full URL (https://...).",
  "event.errInvalidStart": "Invalid start date/time.",
  "event.errStartDateRequired": "Start date is required.",
  "event.errTaglineLength": "Tagline must be 255 characters or fewer.",
  "event.errTitleLength": "Title must be between 4 and 512 characters.",
  "event.errValidEmail": "Enter a valid email address.",
  "event.fieldAddress": "Address",
  "event.fieldCity": "City",
  "event.fieldCountry": "Country",
  "event.fieldDescription": "Description",
  "event.fieldEndDate": "End date",
  "event.fieldEndTime": "End time",
  "event.fieldOrganizerEmail": "Organizer email",
  "event.fieldOrganizerName": "Organizer name",
  "event.fieldRegistrationUrl": "Registration / ticket URL",
  "event.fieldStartDate": "Start date",
  "event.fieldStartTime": "Start time",
  "event.fieldTagline": "Tagline",
  "event.fieldTimezone": "Timezone",
  "event.fieldTitle": "Event title",
  "event.fieldVenue": "Venue name",
  "event.fieldWebsite": "Event website",
  "event.findNextEdition": "Find the next edition and other upcoming events across the {site} hub.",
  "event.followLive": "Follow live",
  "event.formatAny": "Any format",
  "event.formatHybrid": "Hybrid",
  "event.formatInPerson": "In-person",
  "event.formatVirtual": "Virtual",
  "event.freeEntry": "Free entry",
  "event.fromTheFloor": "From the floor",
  "event.getDirections": "Get directions",
  "event.getYourTicket": "Get your ticket",
  "event.goingNextYear": "Going next year?",
  "event.highlights": "Event highlights",
  "event.hostBandBlurb": "List your conference, expo or forum in front of the region's industry leaders, engineers and decision-makers.",
  "event.hostYourEventOn": "Host your event on {site}",
  "event.justAnnounced": "Just announced",
  "event.liveCoverageMany": "Live coverage in progress — {n} updates",
  "event.liveCoverageOne": "Live coverage in progress — 1 update",
  "event.liveFeed": "Live feed",
  "event.liveFeedEmpty": "The live feed will appear here as soon as our correspondents start posting.",
  "event.livePhoto": "Live photo",
  "event.liveVideo": "Live video",
  "event.mapOf": "Map of {place}",
  "event.mostAnticipatedEvents": "Most anticipated events",
  "event.nRemaining": "{n} remaining",
  "event.nSpeakers": "{n} Speakers",
  "event.nUpdates": "{n} updates",
  "event.newDeal": "New deal",
  "event.notFoundBody": "The event you're looking for doesn't exist or has been removed.",
  "event.nowHappening": "Now happening",
  "event.oneSpeaker": "1 Speaker",
  "event.oneUpdate": "1 update",
  "event.openInMaps": "Open the location in your maps app for routes and travel time.",
  "event.organizerEmailHint": "Use a domain that matches the organizer where possible — it helps approval go faster.",
  "event.organizerNamePlaceholder": "Org name or your name",
  "event.pinned": "Pinned",
  "event.priceAny": "Any price",
  "event.priceFree": "Free only",
  "event.readFullRecapOf": "Read the full recap of {title}",
  "event.readRecap": "Read recap",
  "event.recapEmpty": "This event has finished. Recordings and a recap will appear here if the organiser publishes them.",
  "event.register": "Register",
  "event.rssAria": "Subscribe to live coverage RSS feed",
  "event.rssTitle": "RSS feed of live coverage",
  "event.salesEnd": "Sales end {date}",
  "event.sectionBasics": "The basics",
  "event.sectionBasicsHint": "Title and a short summary of what the event is about.",
  "event.sectionLinks": "Links",
  "event.sectionLinksHint": "Optional but recommended — the AI moderator weighs real websites positively.",
  "event.sectionOrganizer": "Organizer",
  "event.sectionOrganizerHint": "Who's running this. We'll use this if we need to reach out with questions.",
  "event.sectionWhen": "When",
  "event.sectionWhenHint": "Leave the end date blank for a single-day event.",
  "event.sectionWhere": "Where",
  "event.sectionWhereHint": "Venue + address for in-person events. Leave blank for fully virtual.",
  "event.selectCountry": "Select country",
  "event.sessionRecordings": "Session recordings",
  "event.shareSession": "Share session",
  "event.shareSpeaker": "Share speaker",
  "event.shareThisSession": "Share this session",
  "event.shareX": "Share {name}",
  "event.soldOut": "Sold out",
  "event.speakersTba": "The speaker line-up hasn't been announced yet.",
  "event.sponsoredBy": "Sponsored by",
  "event.statAttendees": "Attendees",
  "event.statDealAnnounced": "Deal announced",
  "event.statDealsAnnounced": "Deals announced",
  "event.statLiveUpdate": "Live update",
  "event.statLiveUpdates": "Live updates",
  "event.statSession": "Session",
  "event.statSessions": "Sessions",
  "event.submitAnother": "Submit another event",
  "event.submitApprovedNote": "If approved, it will appear on the public Events page and you'll see it listed under your account submissions.",
  "event.submitBody": "Your event has been submitted (ref {ref}). It will go through AI review first, then a human editor.",
  "event.submitEvent": "Submit event",
  "event.submitFailed": "Submission failed. Please try again.",
  "event.submitIntro": "Tell us about your tech event and we'll review it for the Events Hub. Conferences, webinars, hackathons, meetups — bring it on.",
  "event.submitReviewNotice": "Submissions are checked by AI for spam/test entries, then reviewed by an editor. You'll see your event live within 1–2 business days if everything checks out.",
  "event.submitThanks": "Thanks — we got it",
  "event.submitting": "Submitting…",
  "event.tabAgenda": "Agenda",
  "event.tabFaqs": "FAQs",
  "event.tabLive": "Live",
  "event.tabOverview": "Overview",
  "event.tabRecap": "Recap",
  "event.tabSideEvents": "Side Events",
  "event.tabSpeakers": "Speakers",
  "event.tabTickets": "Tickets",
  "event.tabVenue": "Venue",
  "event.taglineHint": "One-line headline (optional, max 255 chars).",
  "event.taglinePlaceholder": "The largest tech event in the MENA region",
  "event.theVenue": "the venue",
  "event.ticketsTba": "Ticket details haven't been published yet.",
  "event.timePast": "Past",
  "event.timeUpcoming": "Upcoming",
  "event.titlePlaceholder": "e.g. LEAP 2026",
  "event.typeAny": "Any type",
  "event.typeConference": "Conference",
  "event.typeHackathon": "Hackathon",
  "event.typeMeetup": "Meetup",
  "event.typeOther": "Other",
  "event.typeSummit": "Summit",
  "event.typeWebinar": "Webinar",
  "event.typeWorkshop": "Workshop",
  "event.venuePlaceholder": "e.g. Riyadh Front",
  "event.viaEventbrite": "Tickets sold via Eventbrite.",
  "event.viaLuma": "Register on Luma.",
  "event.viaOrganiser": "Ticket sales handled by the organiser.",
  "event.virtualJoiningDetails": "This is a virtual event — joining details come with your registration.",
  "event.whatToExpect": "What to expect",
  "event.whoShouldAttend": "Who should attend",
  // --- events
  "events.aboutEvent": "About {title}",
  "events.aboutThisEvent": "About this event",
  "events.aboutVenue": "About the venue",
  "events.addToCalendar": "Add to calendar",
  "events.addedConstantly": "New events are added constantly — or submit yours and we'll list it for free.",
  "events.agenda": "Agenda",
  "events.agendaComingSoon": "The agenda isn’t published yet. Sessions will appear here as soon as the organisers confirm them.",
  "events.agendaNotPublished": "The agenda isn't published yet",
  "events.agendaNotPublishedBody": "Sessions and speaking slots will appear here as soon as the organisers confirm them.",
  "events.allEvents": "All events",
  "events.aroundEvent": "Around {title}",
  "events.backToEvent": "Back to event",
  "events.backToEventPage": "Back to event page",
  "events.backToEvents": "Back to events",
  "events.bookmarkError": "Couldn't update your bookmarks. Please try again.",
  "events.bookmarksStoredOn": "Bookmarks are stored on your {site} account.",
  "events.browseArchive": "Browse the archive for recaps, recordings and our coverage.",
  "events.byTheNumbers": "Event by the numbers",
  "events.checkBackSoon": "Check back shortly — or submit yours and we'll list it for free.",
  "events.clearSearchFor": "Clear search for {query}",
  "events.comingUpNext": "Coming up next",
  "events.coverageArticle": "Article",
  "events.coverageLink": "Link",
  "events.coverageOpen": "Coverage open",
  "events.coveragePressRelease": "Press release",
  "events.coverageReport": "Report",
  "events.coverageSocial": "Social",
  "events.coverageVideo": "Video",
  "events.coveredLiveMany": "{n} events being covered live",
  "events.coveredLiveOne": "1 event being covered live",
  "events.dateTba": "Date TBA",
  "events.dates": "Dates",
  "events.dayN": "Day {n}",
  "events.directions": "Directions",
  "events.ended": "Event ended",
  "events.event": "Event",
  "events.eventPhotos": "Event photos",
  "events.everythingLeftIn": "Everything left in {month}",
  "events.exploreAll": "Explore all",
  "events.featured": "Featured",
  "events.featuredSession": "Featured session",
  "events.featuredSpeakers": "Featured speakers",
  "events.followBlurb": "Speaker announcements, agenda changes and our reporting from the floor — we’ll email you when something happens.",
  "events.followEvent": "Follow {title}",
  "events.followLive": "Follow live coverage",
  "events.followLiveBlurb": "Get every breaking story, funding announcement, and key moment as it happens.",
  "events.followLiveCoverage": "Follow live coverage",
  "events.free": "Free",
  "events.furtherAhead": "Further ahead",
  "events.future": "future.",
  "events.getDirections": "Get directions",
  "events.goToLiveCoverage": "Go to live coverage",
  "events.goingCount": "{n} going",
  "events.heroBlurb": "From global expos to regional forums — find the events that connect the people building the region's industry.",
  "events.imGoing": "I'm going",
  "events.inDays": "In {n} days",
  "events.inDaysHours": "In {d}d {h}h",
  "events.inHoursMins": "In {h}h {m}m",
  "events.inHoursMinutes": "in {h}h {m}m",
  "events.inMinutes": "In {n}m",
  "events.keyFacts": "Key facts",
  "events.keyMoments": "Key moments",
  "events.live": "Live",
  "events.liveAt": "Live at {title}",
  "events.liveCoverage": "Live coverage",
  "events.liveCoverageOf": "Live coverage of {title}",
  "events.liveFeed": "Live feed",
  "events.liveStartsSoon": "Live coverage starts soon",
  "events.liveStartsSoonBody": "Our correspondents will start posting from {event} on {date}. Check back here for breaking news, funding announcements, and key moments.",
  "events.liveUpdate": "Live update",
  "events.liveUpdateFrom": "Live update from {title}",
  "events.mastheadBlurb": "The regional tech calendar in one place — with live reporting from the floor while it's happening.",
  "events.media": "Event media",
  "events.moreSpeakersMany": "More speakers on the programme",
  "events.moreSpeakersOne": "More speaker on the programme",
  "events.nEvents": "{n} events",
  "events.newUpdateMany": "{n} new updates",
  "events.newUpdateOne": "{n} new update",
  "events.newsroomReporting": "Reporting from the {site} newsroom",
  "events.noDescription": "The organiser hasn’t published a description for this event yet.",
  "events.noMatchFilters": "No events match these filters",
  "events.noPastEvents": "No past events on record yet",
  "events.noSessionsForDay": "No sessions scheduled for this day yet.",
  "events.noUpdatesYet": "No updates yet",
  "events.notFound": "Event not found",
  "events.notFoundBody": "The event you're looking for doesn't exist or has been removed.",
  "events.nothingOnCalendar": "Nothing on the calendar right now",
  "events.officialSite": "Official site",
  "events.oneEvent": "1 event",
  "events.oneUpdateFrom": "This is one update from our live coverage",
  "events.openLiveCoverage": "Open live coverage of {title}",
  "events.organiser": "Organiser",
  "events.overview": "Overview",
  "events.pastArchived": "Archived — registration is closed",
  "events.pastEvents": "Past events",
  "events.photoCredit": "Photo:",
  "events.photos": "Photos",
  "events.playVideoN": "Play video {n} of {total}",
  "events.playVideoNamed": "Play video: {name}",
  "events.popularTopics": "Popular topics:",
  "events.pressAndCoverage": "Press & coverage",
  "events.priceFrom": "From {price}",
  "events.publicationAsset": "{site} asset",
  "events.publicationCoverage": "{site} coverage",
  "events.rankedByRsvps": "Ranked by RSVPs on {site}",
  "events.registerOnOrganiserSite": "Register on the organiser’s site",
  "events.registration": "Registration",
  "events.removeFromBookmarks": "Remove {title} from bookmarks",
  "events.removedFromBookmarks": "Removed from bookmarks",
  "events.replay": "Replay",
  "events.restOfCalendar": "The rest of the calendar",
  "events.resultsFor": "Results for “{query}”",
  "events.rsvpAccountNote": "Your RSVP and reminder emails live on your {site} account.",
  "events.rsvpError": "Could not update your RSVP",
  "events.saveEvent": "Save event",
  "events.saveThisEvent": "Save this event",
  "events.saveToBookmarks": "Save {title} to bookmarks",
  "events.savedToBookmarks": "Saved to your bookmarks",
  "events.scrollThumbsLeft": "Scroll thumbnails left",
  "events.scrollThumbsRight": "Scroll thumbnails right",
  "events.sections": "Event sections",
  "events.seoLiveDescription": "Live updates, funding announcements, and key moments from {title}.",
  "events.seoLiveTitle": "{title} — Live coverage",
  "events.sessionCountMany": "{n} sessions",
  "events.sessionCountOne": "{n} session",
  "events.shareEvent": "Share this event",
  "events.showImageN": "Show image {n} of {total}",
  "events.showSlide": "Show {title}",
  "events.signInToRsvp": "Sign in to RSVP",
  "events.signInToSave": "Sign in to save events",
  "events.sponsor": "Sponsor",
  "events.sponsorsAndPartners": "Sponsors & partners",
  "events.startingNow": "Starting now",
  "events.startingSoon": "Starting soon",
  "events.stayInTheLoop": "Stay in the loop",
  "events.submitBandBlurb": "Get it in front of the region's founders, operators and investors. Listing on the {site} events hub is free.",
  "events.tabsAll": "All events",
  "events.tabsConferences": "Conferences",
  "events.tabsHackathons": "Hackathons",
  "events.tabsMeetups": "Meetups",
  "events.tabsSummits": "Summits",
  "events.tabsWebinars": "Webinars",
  "events.tabsWorkshops": "Workshops",
  "events.tba": "TBA",
  "events.tbd": "TBD",
  "events.thisMonth": "This month",
  "events.tierBronze": "Bronze",
  "events.tierGold": "Gold",
  "events.tierPartners": "Partners",
  "events.tierPlatinum": "Platinum",
  "events.tierSilver": "Silver",
  "events.tryWidening": "Try widening your search, or clear the filters to browse the full calendar.",
  "events.upNext": "Up next",
  "events.updateCountMany": "{n} updates",
  "events.updateCountOne": "{n} update",
  "events.updateNotFound": "Update not found",
  "events.updateNotFoundBody": "This live update doesn't exist or has been removed.",
  "events.updatesThisHourMany": "{n} updates this hour",
  "events.updatesThisHourOne": "{n} update this hour",
  "events.venue": "Venue",
  "events.video": "Event video",
  "events.viewAllCoverage": "View all coverage",
  "events.viewAllLiveSessions": "View all live sessions",
  "events.viewAllSpeakers": "View all speakers",
  "events.viewFullAgenda": "View full agenda",
  "events.viewLarger": "View larger: {name}",
  "events.viewPhotoN": "View photo {n} of {total}",
  "events.visitOrganiser": "Visit organiser",
  "events.youAreGoing": "You're going",
  // --- explore
  "explore.companiesDesc": "Contractors, operators & manufacturers",
  "explore.content": "Content",
  "explore.discover": "Discover",
  "explore.ecosystem": "Ecosystem",
  "explore.eventsDesc": "Conferences & meetups",
  "explore.jobsDesc": "Tech career opportunities",
  "explore.newsDesc": "Latest tech news",
  // --- filter
  "filter.allCities": "All Cities",
  "filter.allDepartments": "All Departments",
  "filter.allLevels": "All Levels",
  "filter.allLocations": "All Locations",
  "filter.allTypes": "All Types",
  "filter.anySalary": "Any Salary",
  "filter.anyTime": "Any time",
  "filter.city": "City",
  "filter.clearAllShort": "Clear all",
  "filter.clearN": "Clear {n} filters",
  "filter.clearOne": "Clear 1 filter",
  "filter.datePosted": "Date Posted",
  "filter.experience": "Experience",
  "filter.past24h": "Past 24 hours",
  "filter.pastMonth": "Past month",
  "filter.pastWeek": "Past week",
  "filter.searchCities": "Search cities…",
  "filter.sortBy": "Sort by",
  // --- form
  "form.aboutYou": "About you",
  "form.capacity": "Capacity",
  "form.company": "Company",
  "form.companyName": "Company Name",
  "form.completeRequired": "Please complete all required fields",
  "form.coverImage": "Cover image",
  "form.date": "Date",
  "form.email": "Email",
  "form.emailLabel": "Email *",
  "form.emailRequired": "Email is required",
  "form.endTime": "End time",
  "form.fillRequired": "Please fill in every field marked with *.",
  "form.firstName": "First Name",
  "form.firstNamePlaceholder": "First name",
  "form.fullName": "Full name",
  "form.industry": "Industry",
  "form.jobTitle": "Job Title",
  "form.lastName": "Last Name",
  "form.lastNamePlaceholder": "Last name",
  "form.message": "Message",
  "form.namePlaceholder": "Jane Doe",
  "form.organisation": "Organisation",
  "form.phone": "Phone",
  "form.pleaseSelect": "Please Select",
  "form.registrationUrl": "Registration URL",
  "form.removeImage": "Remove image",
  "form.sending": "Sending…",
  "form.startTime": "Start time",
  "form.submit": "Submit",
  "form.uploadCover": "Upload a cover image (optional, max 5MB)",
  "form.validEmail": "Please enter a valid email address.",
  "form.venue": "Venue",
  "form.yourEmail": "Your email *",
  "form.yourName": "Your name *",
  // --- job
  "job.aboutRole": "About the Role",
  "job.addCoverLetter": "Add cover letter or more details",
  "job.applicants": "Applicants",
  "job.applicationFailed": "Application Failed",
  "job.applicationSentBody": "Your application for {job} has been sent to {company}. The hiring team will review it and get back to you soon.",
  "job.applicationSentToast": "Your application for {job} at {company} has been sent.",
  "job.applicationStarted": "Application started",
  "job.applicationSubmitted": "Application Submitted!",
  "job.applied": "Applied",
  "job.appliedExternally": "Applied externally",
  "job.appliedVia": "Applied via {site}",
  "job.apply": "Apply",
  "job.applyNow": "Apply Now",
  "job.applyOnCompanySite": "Apply on Company Site",
  "job.at": "at",
  "job.backToJob": "Back to Job",
  "job.benefitsPerks": "Benefits & Perks",
  "job.cLevel": "C-Level",
  "job.chooseFile": "Choose File",
  "job.competitionLevel": "Competition Level",
  "job.completeProfile": "Complete Profile",
  "job.contract": "Contract",
  "job.count": "{n} jobs",
  "job.coverLetter": "Cover Letter",
  "job.coverLetterPlaceholder": "Tell the hiring team why you're a great fit for this role...",
  "job.currentCompany": "Current Company",
  "job.currentCompanyPlaceholder": "e.g. Google",
  "job.currentTitle": "Current Title",
  "job.currentTitlePlaceholder": "e.g. Senior Engineer",
  "job.cvAttached": "CV attached",
  "job.cvAttachedBody": "Your CV has been attached to the application.",
  "job.cvAttachedTitle": "CV Attached",
  "job.cvReferenceSaved": "Your CV reference has been saved.",
  "job.cvUploaded": "CV Uploaded",
  "job.cvUploadedBody": "Your CV has been uploaded successfully.",
  "job.department": "Department",
  "job.details": "Job Details",
  "job.director": "Director",
  "job.easyApply": "Easy Apply",
  "job.employmentType": "Employment Type",
  "job.entryLevel": "Entry Level",
  "job.executive": "Executive",
  "job.expectedSalary": "Expected Salary (Annual)",
  "job.experienceLevel": "Experience Level",
  "job.expires": "Expires",
  "job.externalApply": "External Apply",
  "job.fileTooLarge": "File Too Large",
  "job.fileTooLargeBody": "CV must be less than 5MB.",
  "job.foundCount": "{n} jobs found",
  "job.foundOne": "{n} job found",
  "job.freelance": "Freelance",
  "job.fullPage": "Full page",
  "job.fullTime": "Full-time",
  "job.fullyRemote": "Fully Remote",
  "job.hiringInsights": "Hiring Insights",
  "job.hybrid": "Hybrid",
  "job.insights": "Job Insights",
  "job.internship": "Internship",
  "job.interviewing": "Interviewing",
  "job.invalidFileType": "Invalid File Type",
  "job.invalidFileTypeBody": "Please upload a PDF or Word document.",
  "job.junior": "Junior",
  "job.lead": "Lead",
  "job.linkCopied": "Job link copied to clipboard!",
  "job.linkedinProfile": "LinkedIn Profile",
  "job.links": "Links",
  "job.location": "Location",
  "job.manager": "Manager",
  "job.menaRegion": "MENA Region",
  "job.midLevel": "Mid Level",
  "job.mustBeLoggedIn": "You must be logged in to apply.",
  "job.noDescription": "No description provided.",
  "job.noSkills": "No skill tags available yet.",
  "job.noneInStage": "No jobs in this stage yet",
  "job.noticeImmediate": "Immediate",
  "job.noticeNotSpecified": "Not specified",
  "job.noticeOneMonth": "1 Month",
  "job.noticeOneWeek": "1 Week",
  "job.noticePeriod": "Notice Period",
  "job.noticeThreeMonths": "3 Months",
  "job.noticeTwoMonths": "2 Months",
  "job.noticeTwoWeeks": "2 Weeks",
  "job.optionalTag": "(Optional)",
  "job.overview": "Overview",
  "job.pageDescription": "Jobs in construction, energy, infrastructure, manufacturing and logistics across Saudi Arabia, the GCC and MENA — engineering, operations, HSE, project management and more.",
  "job.pageTitle": "Industry Jobs",
  "job.partTime": "Part-time",
  "job.pipeline": "Your job pipeline",
  "job.portfolioWebsite": "Portfolio / Website",
  "job.posted": "Posted",
  "job.postedAgo": "Posted {time}",
  "job.professionalDetails": "Professional Details",
  "job.quickApply": "Quick Apply",
  "job.quickApplyBody": "Your profile will be shared with the employer. Add a note or expand the form for more details.",
  "job.quickApplyReady": "Quick Apply Ready",
  "job.quickNote": "Quick Note (Optional)",
  "job.quickNotePlaceholder": "Add a brief note to your application...",
  "job.recommendedTag": "(Recommended)",
  "job.remote": "Remote",
  "job.remoteFriendly": "Remote Friendly",
  "job.remotePolicy": "Remote Policy",
  "job.requiredSkills": "Required Skills",
  "job.requirements": "Requirements",
  "job.responsibilities": "Responsibilities",
  "job.resumeCv": "Resume / CV",
  "job.salary": "Salary",
  "job.salaryPlaceholder": "e.g. 80000",
  "job.salaryRange": "Salary Range",
  "job.saved": "Saved",
  "job.searchPlaceholder": "Search by title, company, or keyword...",
  "job.seen": "Seen",
  "job.selectToSeeDetails": "Select a job to see details",
  "job.senior": "Senior",
  "job.seniority": "Seniority",
  "job.seniorityLevel": "Seniority Level",
  "job.seoApplyNow": "Apply now on {site}.",
  "job.seoDescription": "{title} job opportunity at {company}.",
  "job.seoLocation": "Location: {location}.",
  "job.seoSalary": "Salary: {salary}.",
  "job.seoTitle": "{title} at {company}",
  "job.shareJob": "Share Job",
  "job.skillsTags": "Skills & Tags",
  "job.submitApplication": "Submit Application",
  "job.submitError": "Something went wrong. Please try again.",
  "job.type": "Job Type",
  "job.uploadCvHint": "Upload your CV (PDF or Word, max 5MB)",
  "job.uploadCvToApply": "Please upload your CV to apply.",
  "job.views": "Views",
  "job.viewsN": "{n} views",
  "job.vp": "VP",
  "job.workStyle": "Work Style",
  "job.yearsExperience": "Years of Experience",
  "job.yearsExperiencePlaceholder": "e.g. 5",
  // --- legal
  "legal.placeholderNotice": "Placeholder — to be reviewed by legal counsel",
  "legal.reviewRequired": "This is placeholder content. Final legal review required before public launch.",
  "legal.reviewRequiredBody": "Nothing on this page is legal advice. Each section is a working draft and will be replaced with counsel-reviewed text prior to launch.",
  "legal.terms": "Terms",
  // --- live
  "live.breaking": "BREAKING",
  "live.copyPermalink": "Copy link to this update",
  "live.fundingAnnounced": "Funding announced",
  "live.newDeal": "New deal",
  "live.openFullImage": "Open full image",
  "live.photoAlt": "Live photo",
  "live.pinned": "Pinned key moment",
  "live.raises": "raises {amount}",
  "live.relatedLink": "Related link",
  "live.session": "Session",
  "live.sponsored": "Sponsored",
  "live.updateAlt": "Update image",
  "live.videoTitle": "Live video",
  "live.viewOnX": "View post on X",
  "live.watchVideo": "Watch video",
  // --- nav
  "nav.home": "Home",
  "nav.siteHome": "{site} home",
  // --- newsletter
  "newsletter.alreadySubscribed": "Already subscribed",
  "newsletter.alreadySubscribedBody": "We've got you. Check your inbox for our most recent issue.",
  "newsletter.asPosted": "As posted",
  "newsletter.browse": "Browse newsletters",
  "newsletter.byOurNewsroom": "Written by our newsroom",
  "newsletter.couldNotSubscribe": "Could not subscribe",
  "newsletter.emailAddress": "Email address",
  "newsletter.energyBrief": "Energy Brief",
  "newsletter.energyDetail": "Oil & gas, power, utilities and renewables: upstream developments, offtake deals, and the policy moves shaping regional energy.",
  "newsletter.eventsDetail": "Upcoming conferences, exhibitions, and industry gatherings across Saudi Arabia, the GCC, and MENA.",
  "newsletter.everyMorning": "Every morning",
  "newsletter.failed": "Subscription failed",
  "newsletter.freeToRead": "Free to read",
  "newsletter.getItByEmail": "Get it by email",
  "newsletter.heroBody": "Contract awards, project milestones, energy moves, and the people behind them — in one concise read.",
  "newsletter.heroTitle": "The Industrial Economy, Every Morning",
  "newsletter.jobsDetail": "New roles across the industries we cover — engineering, construction, energy, logistics, and operations.",
  "newsletter.monthly": "Monthly",
  "newsletter.morningBriefing": "Your morning briefing",
  "newsletter.noSpam": "No spam, ever",
  "newsletter.preferencesSaved": "Preferences saved",
  "newsletter.preferencesSavedBody": "You'll receive {n} newsletter(s). Enter your email above to subscribe.",
  "newsletter.projectsDetail": "Major project awards, tenders, and milestones across construction and infrastructure — tracked from announcement to delivery.",
  "newsletter.sampleEnergy": "Energy: capacity additions and offtake agreements",
  "newsletter.sampleEnergySub": "Power, oil & gas, and renewables in brief",
  "newsletter.sampleHeadline": "Main contract awarded on a giga-project package",
  "newsletter.sampleIntro": "A sample of how {name} lands in your inbox",
  "newsletter.sampleLede": "The day's most consequential story, with the parties, scope, and what it signals for the wider program...",
  "newsletter.samplePeople": "People: appointments across the sector",
  "newsletter.samplePeopleSub": "Who's moving where, and why it matters",
  "newsletter.selectListsBody": "Select the briefings that match your work. You can update your preferences anytime.",
  "newsletter.subscribeToCount": "Subscribe to {n} newsletters",
  "newsletter.unsubscribeAnytimeShort": "Unsubscribe anytime",
  "newsletter.weekly": "Weekly",
  "newsletter.whatToExpect": "What to Expect",
  "newsletter.youreIn": "You're in",
  "newsletter.youreInBody": "Welcome email on its way. Check your inbox in a minute.",
  // --- person
  "person.about": "About",
  "person.achievements": "Achievements & recognition",
  "person.advisor": "Advisor",
  "person.advisoryRoles": "Advisory roles",
  "person.angel": "Angel",
  "person.angelInvestor": "Angel investor",
  "person.at": "at",
  "person.boardAdvisory": "Board & advisory",
  "person.boardMember": "Board member",
  "person.boardPositions": "Board positions",
  "person.bookCall": "Book a call",
  "person.careerTimeline": "Career timeline",
  "person.companiesFounded": "Companies founded",
  "person.contact": "Contact",
  "person.contactBody": "Send a message to {name}. They will be notified via email.",
  "person.contactName": "Contact {name}",
  "person.current": "Current",
  "person.dataTransparency": "Data transparency",
  "person.dataTransparencyBody": "This profile is compiled from public sources and verified data.",
  "person.details": "Details",
  "person.education": "Education",
  "person.experience": "Experience",
  "person.expertise": "Expertise",
  "person.followingName": "Following {name}",
  "person.founder": "Founder",
  "person.functionalStrengths": "Functional strengths",
  "person.interests": "Interests",
  "person.investments": "Investments",
  "person.languages": "Languages",
  "person.lastUpdated": "Last updated",
  "person.linkCopied": "Profile link copied",
  "person.location": "Location",
  "person.message": "Message",
  "person.messagePlaceholder": "Write your message…",
  "person.messageSent": "Message sent",
  "person.nInvestments": "{n} investments",
  "person.nationality": "Nationality",
  "person.network": "Network",
  "person.noCareerData": "No career or education data available yet.",
  "person.noInvestmentData": "No investment or company data available yet.",
  "person.noNetworkData": "No network data available yet.",
  "person.onLinkedin": "{name} on LinkedIn",
  "person.onTwitter": "{name} on X / Twitter",
  "person.openTo": "Open to",
  "person.openToIntros": "Open to intros",
  "person.organization": "Organization",
  "person.personalInvestments": "Personal investments",
  "person.present": "Present",
  "person.primaryRole": "Primary role",
  "person.quickInfo": "Quick info",
  "person.regions": "Regions",
  "person.sectors": "Sectors",
  "person.sendMessage": "Send message",
  "person.shareProfile": "Share profile",
  "person.signInToFollow": "Please sign in to follow people.",
  "person.similarPeople": "Similar people",
  "person.speakingAt": "Speaking At",
  "person.tabCareer": "Career & Education",
  "person.tabInvestments": "Investments & Companies",
  "person.tabNetwork": "Network & Influence",
  "person.tabOverview": "Overview",
  "person.unfollowedName": "Unfollowed {name}",
  "person.verified": "Verified",
  "person.views": "Views",
  "person.website": "{name}'s website",
  "person.willBeNotified": "{name} will be notified.",
  "person.yourEmail": "Your email",
  // --- privacy
  "privacy.children1": "The Service is not directed to children under the age required by law in your jurisdiction. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, contact us so we can remove it.",
  "privacy.childrenTitle": "8. Children's Privacy",
  "privacy.collectAccount": "name, email, password hash, and basic profile fields you provide if you register for an account.",
  "privacy.collectAccountLabel": "Account information:",
  "privacy.collectForms": "information you send us through our contact and advertising inquiry forms, such as your name, email, company, and message.",
  "privacy.collectFormsLabel": "Form submissions:",
  "privacy.collectIntro": "We collect the following categories of information:",
  "privacy.collectNewsletter": "your email address, the newsletters you select, and your consent preferences.",
  "privacy.collectNewsletterLabel": "Newsletter subscription details:",
  "privacy.collectTitle": "1. Information We Collect",
  "privacy.collectUsage": "device and browser information, pages visited, and similar analytics data collected through cookies and comparable technologies.",
  "privacy.collectUsageLabel": "Usage data:",
  "privacy.contact1": "Privacy questions, requests, or complaints can be sent to",
  "privacy.contactTitle": "9. Contact",
  "privacy.cookiePreferences": "cookie preferences",
  "privacy.cookies1": "We use cookies and similar technologies for essential functionality, analytics, and (where you opt in) advertising and marketing. You can revisit your choices at any time via",
  "privacy.cookiesTitle": "6. Cookies",
  "privacy.lead": "This Privacy Policy explains how {legalName} (“{site}”) collects, uses, and shares information when you use {domain} and the services we provide through it (the “Service”). It applies to readers, newsletter subscribers, and visitors. Your use of the Service is also governed by our",
  "privacy.retention1": "We retain personal data for as long as your account or subscription is active or as needed to provide the Service. After account closure or unsubscription, we delete or anonymize data within a reasonable period, except where retention is required by law.",
  "privacy.retentionTitle": "4. Data Retention",
  "privacy.rightAccess": "Access",
  "privacy.rightAccessBody": "request a copy of the personal data we hold about you.",
  "privacy.rightErasure": "Erasure",
  "privacy.rightErasureBody": "ask us to delete your account, subscription, and associated data.",
  "privacy.rightPortability": "Portability",
  "privacy.rightPortabilityBody": "receive your data in a machine-readable format.",
  "privacy.rightRectification": "Rectification",
  "privacy.rightRectificationBody": "correct inaccurate data via your account or by contacting us.",
  "privacy.rightsContact": "To exercise any of these rights, contact us at",
  "privacy.rightsIntro": "Depending on your jurisdiction you may have the following rights:",
  "privacy.rightsTitle": "5. Your Rights",
  "privacy.rightsUnsubscribe": "You can unsubscribe from any newsletter at any time using the link in the email footer.",
  "privacy.sharing1": "We share information with service providers who help us run the Service — for example, email delivery, hosting and infrastructure, and analytics vendors. These providers process data on our behalf and are not permitted to use it for their own purposes.",
  "privacy.sharing2": "We do not sell personal information. A finalized list of sub-processors with contractual commitments will be published prior to launch.",
  "privacy.sharingTitle": "3. Data Sharing",
  "privacy.transfers1": "Our readers, and the service providers we rely on, are located in multiple countries. Personal data may therefore be processed outside the country in which you live. Where personal data is transferred between jurisdictions, we rely on appropriate safeguards such as standard contractual clauses or equivalent mechanisms recognized under applicable law.",
  "privacy.transfersTitle": "7. International Transfers",
  "privacy.updates1": "We may update this Privacy Policy from time to time. Material changes will be announced on this page and, where appropriate, through additional notice. The “Last updated” date above will always reflect the most recent revision.",
  "privacy.updatesTitle": "10. Updates to this Policy",
  "privacy.useAdvertising": "Serve and measure advertising on the site, consistent with your cookie choices.",
  "privacy.useCommunicate": "Communicate with you about your account and the Service.",
  "privacy.useDeliver": "Deliver the newsletters and briefings you subscribe to.",
  "privacy.useIntro": "We use the information we collect to:",
  "privacy.useOperate": "Operate, secure, and improve the Service, including understanding which coverage our readers find useful.",
  "privacy.useRespond": "Respond to your inquiries, tips, and feedback.",
  "privacy.useTitle": "2. How We Use Information",
  // --- profile
  "profile.aboutYou": "About you",
  "profile.aboutYouDesc": "Your basic information and background",
  "profile.addInterestPlaceholder": "Type to search or add an interest…",
  "profile.addLocationPlaceholder": "Type to search or add a location…",
  "profile.bio": "Bio",
  "profile.bioPlaceholder": "Tell us about your experience and what you're looking for…",
  "profile.chooseFile": "Choose file",
  "profile.companyPlaceholder": "e.g. Careem",
  "profile.completion": "Profile completion",
  "profile.currentLocation": "Current location",
  "profile.cvComingSoon": "CV management coming soon",
  "profile.cvUploadComingSoon": "CV upload coming soon",
  "profile.dropResume": "Drop your resume here or click to upload",
  "profile.editDetails": "Edit {name} details, add content, and keep information up to date",
  "profile.editProfile": "Edit Profile",
  "profile.editSection": "Edit {section}",
  "profile.editThisSection": "Edit this section",
  "profile.emailLocked": "Email cannot be changed",
  "profile.fullName": "Full name",
  "profile.fullNamePlaceholder": "Enter your full name",
  "profile.interestsDesc": "Select topics you're interested in for better recommendations",
  "profile.interestsSkills": "Interests & skills",
  "profile.jobTitle": "Job title",
  "profile.jobTitlePlaceholder": "e.g. Product Manager",
  "profile.locationPlaceholder": "e.g. Dubai, UAE",
  "profile.personalWebsite": "Personal website",
  "profile.preferredLocations": "Preferred work locations",
  "profile.preferredLocationsDesc": "Where would you like to work?",
  "profile.professional": "Professional information",
  "profile.professionalDesc": "Your current role and company",
  "profile.replace": "Replace",
  "profile.resume": "Resume / CV",
  "profile.resumeDesc": "Upload your resume for easy job applications",
  "profile.resumeFormats": "PDF, DOC, or DOCX up to 5MB",
  "profile.resumeUploaded": "Resume uploaded",
  "profile.salary": "Salary expectations",
  "profile.salaryDesc": "This information is kept private and only used for job matching",
  "profile.salaryMax": "Maximum (USD/year)",
  "profile.salaryMaxPlaceholder": "e.g. 120000",
  "profile.salaryMin": "Minimum (USD/year)",
  "profile.salaryMinPlaceholder": "e.g. 80000",
  "profile.save": "Save profile",
  "profile.saveFailed": "Could not save profile",
  "profile.saveHint": "All changes are saved when you click Save",
  "profile.saved": "Profile saved",
  "profile.saving": "Saving…",
  "profile.sectionsCompleted": "{done} of {total} sections completed",
  "profile.social": "Social & web presence",
  "profile.socialDesc": "Connect your online profiles",
  "profile.subtitle": "Complete your profile to get better job matches and recommendations",
  "profile.title": "Your profile",
  "profile.twitterPlaceholder": "username (without @)",
  "profile.viewResume": "View your resume",
  "profile.youManage": "You manage this profile",
  // --- search
  "search.minCharacters": "Enter at least 2 characters to search across all content",
  "search.newsCompaniesPeople": "Search news, companies, people...",
  "search.noResultsFor": "No results found for \"{query}\"",
  "search.nothingMatching": "We couldn't find anything matching \"{query}\". Try different keywords.",
  "search.openJobs": "Open Jobs",
  "search.recent": "Recent",
  "search.resultsFor": "{count} results for \"{query}\"",
  "search.searching": "Searching...",
  "search.trendingTopics": "Trending Topics",
  "search.typeArticle": "Article",
  "search.typeCompany": "Company",
  "search.typeEvent": "Event",
  "search.typeJob": "Job",
  "search.typePerson": "Person",
  "search.upcomingEvents": "Upcoming Events",
  // --- share
  "share.copy": "Copy",
  "share.copyFailed": "Couldn't copy automatically",
  "share.copyLink": "Copy link",
  "share.copyLinkFailed": "Could not copy link",
  "share.linkCopied": "Link copied",
  "share.onLinkedIn": "Share on LinkedIn",
  "share.onWhatsApp": "Share on WhatsApp",
  "share.onX": "Share on X",
  "share.session": "{name} — {event}",
  "share.sessionOn": "{name} — {event} on {date}",
  "share.speaker": "{name} is speaking at {event}",
  "share.speakerOn": "{name} is speaking at {event} on {date}",
  "share.tweet": "Tweet",
  // --- sideEvent
  "sideEvent.capacityPositive": "Capacity must be a positive number.",
  "sideEvent.coverAlt": "Side event cover",
  "sideEvent.ctaBlurb": "Add your workshop, dinner, or meetup to this page. Free, takes a minute, and no account needed — our editors review every submission.",
  "sideEvent.ctaEmpty": "No side events listed yet",
  "sideEvent.ctaRunning": "Running your own side event?",
  "sideEvent.descriptionLabel": "Description *",
  "sideEvent.descriptionPlaceholder": "What is it, who is it for, and what should people expect?",
  "sideEvent.free": "Free",
  "sideEvent.host": "Host a side event",
  "sideEvent.hostBlurb": "Running a workshop, dinner, or party around this event? Tell us about it and we'll list it here once our editors have reviewed it. No account needed.",
  "sideEvent.isFreeLabel": "This side event is free to attend",
  "sideEvent.moderationNote": "Submissions are reviewed by our editors before they appear.",
  "sideEvent.nameLabel": "Side event name *",
  "sideEvent.namePlaceholder": "Founders' breakfast",
  "sideEvent.orgPlaceholder": "Company, community, or fund",
  "sideEvent.paid": "Paid",
  "sideEvent.places": "{n} places",
  "sideEvent.register": "Register",
  "sideEvent.selectType": "Select a type",
  "sideEvent.submitAnother": "Submit another",
  "sideEvent.submitForReview": "Submit for review",
  "sideEvent.submittedIntro": "Thanks — our team will review it shortly. Your side event is",
  "sideEvent.submittedNotLive": "not live yet",
  "sideEvent.submittedOutro": "and will only appear on this page once an editor approves it. We'll email {email} either way.",
  "sideEvent.submittedOutroNoEmail": "and will only appear on this page once an editor approves it. We'll email you either way.",
  "sideEvent.submittedTitle": "Submitted for review",
  "sideEvent.toastSubmitFailed": "Could not submit side event",
  "sideEvent.toastSubmitted": "Side event submitted for review",
  "sideEvent.typeDinner": "Dinner",
  "sideEvent.typeLabel": "Type *",
  "sideEvent.typeNetworking": "Networking",
  "sideEvent.typeOther": "Other",
  "sideEvent.typeParty": "Party",
  "sideEvent.typeSideEvent": "Side event",
  "sideEvent.typeTour": "Tour",
  "sideEvent.typeWorkshop": "Workshop",
  "sideEvent.venuePlaceholder": "Where is it happening?",
  // --- sitemap
  "sitemap.aboutDesc": "Learn about {site}",
  "sitemap.advertiseDesc": "Advertising opportunities",
  "sitemap.authorPages": "Author Pages",
  "sitemap.companyProfiles": "Company Profiles",
  "sitemap.contactDesc": "Get in touch with us",
  "sitemap.dashboardDesc": "Your personalized dashboard",
  "sitemap.dynamicPages": "Dynamic Pages",
  "sitemap.dynamicPagesIntro": "In addition to the pages listed above, {site} has dynamic content pages including:",
  "sitemap.eventDetails": "Event Details",
  "sitemap.eventsDesc": "Upcoming tech events",
  "sitemap.intro": "A complete overview of all pages and sections on {site}.",
  "sitemap.jobDetails": "Job Details",
  "sitemap.jobsDesc": "Browse tech job opportunities",
  "sitemap.legal": "Legal",
  "sitemap.mainPages": "Main Pages",
  "sitemap.newsHomepage": "News Homepage",
  "sitemap.newsHomepageDesc": "Latest industry news and updates",
  "sitemap.newsletterDesc": "Subscribe to our newsletter",
  "sitemap.peopleDesc": "Connect with tech professionals",
  "sitemap.peopleProfiles": "People Profiles",
  "sitemap.privacyDesc": "How we handle your data",
  "sitemap.profileDesc": "Manage your profile settings",
  "sitemap.termsDesc": "Terms and conditions",
  // --- sort
  "sort.mostRecent": "Most Recent",
  "sort.mostViewed": "Most Viewed",
  "sort.salaryHighLow": "Salary: High to Low",
  "sort.salaryLowHigh": "Salary: Low to High",
  "sort.titleAz": "Title: A-Z",
  // --- state
  "state.backToCompanies": "Back to Companies",
  "state.backToEvents": "Back to events",
  "state.backToJobs": "Back to Jobs",
  "state.backToPeople": "Back to people",
  "state.companyNotFound": "Company Not Found",
  "state.companyNotFoundBody": "The company you're looking for doesn't exist or has been removed.",
  "state.errorTryAgain": "Something went wrong. Please try again.",
  "state.eventNotFound": "Event not found",
  "state.imageUnavailable": "Image unavailable",
  "state.jobNotFound": "Job Not Found",
  "state.jobNotFoundBody": "The job you're looking for doesn't exist or has been removed.",
  "state.noJobs": "No jobs found",
  "state.personNotFound": "Person not found",
  "state.personNotFoundBody": "The person you're looking for doesn't exist.",
  "state.reloadPage": "Reload Page",
  "state.tryAgainMoment": "Try again in a moment.",
  "state.unexpectedError": "An unexpected error occurred.",
  "state.uploading": "Uploading…",
  // --- stats
  "stats.attendee": "Expected attendee",
  "stats.attendees": "Expected attendees",
  "stats.countries": "Countries",
  "stats.country": "Country",
  "stats.dealAnnounced": "Deal announced",
  "stats.dealsAnnounced": "Deals announced",
  "stats.exhibitor": "Exhibitor",
  "stats.exhibitors": "Exhibitors",
  "stats.investor": "Investor",
  "stats.investors": "Investors",
  "stats.speaker": "Speaker",
  "stats.speakers": "Speakers",
  "stats.track": "Track",
  "stats.tracks": "Tracks",
  // --- terms
  "terms.acceptableUse1": "You agree not to misuse the Service. Examples of prohibited activity include scraping or republishing our content without permission, posting unlawful or infringing content, harassing other users, attempting to gain unauthorized access, or interfering with the Service's operation.",
  "terms.acceptableUseTitle": "4. Acceptable Use",
  "terms.acceptance1": "By accessing {domain} or otherwise using the services provided by {legalName} (the “Service”), you agree to be bound by these Terms of Service and any policies referenced here. If you do not agree, you must not use the Service.",
  "terms.acceptanceTitle": "1. Acceptance of Terms",
  "terms.accounts1": "Some features may require an account or newsletter subscription. You are responsible for the accuracy of the information you provide and for keeping your credentials secure. You must notify us promptly of any unauthorized access to your account.",
  "terms.accountsTitle": "3. User Accounts",
  "terms.changes1": "We may update these Terms from time to time. We will post the updated version on this page and, where appropriate, notify you. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.",
  "terms.changesTitle": "12. Changes to Terms",
  "terms.contact1": "Questions about these Terms can be sent to",
  "terms.contactTitle": "13. Contact",
  "terms.description1": "{site} is an online publication covering the industrial economy — construction, infrastructure, energy, manufacturing, logistics, and related sectors. The Service includes news and analysis, company and people coverage, project tracking, event listings, job listings, and email newsletters. Features may change over time as the Service evolves.",
  "terms.descriptionTitle": "2. Description of Service",
  "terms.disclaimers1": "The Service is provided “as is” without warranties of any kind, express or implied, to the maximum extent permitted by applicable law.",
  "terms.disclaimersTitle": "8. Disclaimers",
  "terms.editorial1": "Content published on the Service is provided for general information only. It does not constitute professional, financial, investment, or legal advice, and should not be relied upon as the basis for any commercial decision. Sponsored and branded content is clearly labelled as such.",
  "terms.editorialTitle": "6. Editorial Content",
  "terms.governingLaw1": "These Terms are governed by applicable law in the jurisdiction in which {legalName} is established, without regard to conflict of law principles. Specific venue and jurisdiction will be confirmed in the final version of these Terms.",
  "terms.governingLawTitle": "11. Governing Law",
  "terms.ip1": "{legalName} and its licensors retain all rights in the Service, including its software, branding, and editorial content. You retain ownership of content you submit, and grant {legalName} a license to host, process, and display it for the purpose of providing the Service.",
  "terms.ipTitle": "5. Intellectual Property",
  "terms.lead": "These Terms of Service govern your access to and use of {site}, operated by {legalName}. Please read them carefully.",
  "terms.liability1": "To the fullest extent permitted by law, {legalName} will not be liable for indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Service.",
  "terms.liabilityTitle": "9. Limitation of Liability",
  "terms.privacy1": "Your use of the Service is also governed by our",
  "terms.privacy2": ", which explains how we collect, use, and share information.",
  "terms.privacyTitle": "7. Privacy",
  "terms.termination1": "We may suspend or terminate your access to the Service if you violate these Terms or if continued provision of the Service is not reasonably practical. You may close your account or unsubscribe from our newsletters at any time.",
  "terms.terminationTitle": "10. Termination",
  // --- ticket
  "ticket.addTicketFirst": "Add at least one ticket before applying a code",
  "ticket.appliedOff": "applied — {amount} off",
  "ticket.checkoutBlurb": "Pick your tickets and we'll hand you off to Stripe to complete payment.",
  "ticket.checkoutFailed": "Could not start checkout",
  "ticket.codeLabel": "Code",
  "ticket.contactOrganiser": "Please contact the organiser to complete your purchase.",
  "ticket.continueCheckout": "Continue to checkout",
  "ticket.decrease": "Decrease {name}",
  "ticket.discount": "Discount",
  "ticket.enterPromo": "Enter a promo code first",
  "ticket.increase": "Increase {name}",
  "ticket.maxPerOrder": "Max {n} per order",
  "ticket.noCheckoutUrl": "Stripe did not return a checkout URL",
  "ticket.noneOnSale": "No ticket tiers are on sale right now.",
  "ticket.pickTicket": "Pick at least one ticket",
  "ticket.promoCode": "Promo code",
  "ticket.promoFailed": "Promo code could not be applied",
  "ticket.redirecting": "Redirecting…",
  "ticket.remaining": "{n} remaining",
  "ticket.soldOut": "Sold out",
  "ticket.subtotal": "Subtotal",
  "ticket.total": "Total",
  // --- tickets
  "tickets.checkoutCancelled": "Checkout cancelled",
  "tickets.confirmationSentTo": "Confirmation sent to",
  "tickets.confirmed": "You're going!",
  "tickets.discount": "Discount",
  "tickets.heading": "Tickets",
  "tickets.missingSession": "Missing session id",
  "tickets.missingSessionBody": "We couldn't find a checkout session reference. If you just paid, please check your email for a confirmation.",
  "tickets.noCharge": "No charge was made. You can try again from the event page.",
  "tickets.orderConfirmed": "Order confirmed",
  "tickets.orderNotFound": "Order not found",
  "tickets.orderNotFoundBody": "We couldn't find this order yet. Please refresh in a moment, or check your email — we'll send a confirmation as soon as the payment clears.",
  "tickets.orderRefunded": "Order refunded",
  "tickets.orderSummaryMany": "Order #{id} · {n} tickets · {total} paid",
  "tickets.orderSummaryOne": "Order #{id} · {n} ticket · {total} paid",
  "tickets.paymentFailed": "Payment failed",
  "tickets.processing": "Processing your order",
  "tickets.processingBody": "Stripe is confirming your payment. This usually takes a few seconds. You'll receive an email receipt as soon as it clears.",
  "tickets.subtotal": "Subtotal",
  "tickets.total": "Total",
  // --- time
  "time.daysAgo": "{n}d ago",
  "time.hoursAgo": "{n}h ago",
  "time.justNow": "Just now",
  "time.monthsAgo": "{n}mo ago",
  "time.recently": "Recently",
  "time.today": "Today",
  "time.weeksAgo": "{n}w ago",
  "time.yearsAgo": "{n}y ago",
  "time.yesterday": "Yesterday",
  // --- upload
  "upload.chooseImage": "Please choose an image file",
  "upload.imageFailed": "Image upload failed — you can submit without one",
  "upload.imageTooLarge": "Images must be under 5MB",
  "upload.imageUploaded": "Image uploaded",
  "events.dateTbd": "Date TBD",
  "events.online": "Online",
  "events.locationTbd": "Location TBD",
} as const;

export type UiKey = keyof typeof UI_STRINGS;

/**
 * Fill {placeholders}. Kept deliberately dumb — no plural rules, no dates.
 * Arabic pluralisation has six forms and getting it half-right is worse than
 * not attempting it, so anything genuinely plural-sensitive gets its own key
 * rather than a rule engine.
 */
export function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (m, k) =>
    vars[k] === undefined ? m : String(vars[k]),
  );
}
