/**
 * The site's own words.
 *
 * Everything a reader sees that is not article copy: navigation, buttons,
 * labels, the footer. Translating 268 articles and leaving "Share:" and
 * "Read more" in English produces a page that is Arabic in the middle and
 * English around the edges, which reads worse than either.
 *
 * The English here is the source of truth and the fallback. A locale
 * translates as much of it as it has, key by key, and anything untranslated
 * shows in English rather than showing a key.
 *
 * Keys are dotted and grouped by where the string appears, so a translator
 * working down the list moves through the page rather than through the
 * codebase.
 */

export const UI_STRINGS = {
  // -------------------------------------------------------------- header
  "nav.search": "Search",
  "nav.searchPlaceholder": "Search {site}",
  "nav.signIn": "Sign in",
  "nav.signOut": "Sign out",
  "nav.account": "Account",
  "nav.createAccount": "Create account",
  "nav.profile": "Profile",
  "nav.dashboard": "Dashboard",
  "nav.myContent": "My content",
  "nav.menu": "Menu",
  "nav.close": "Close",
  "nav.language": "Language",
  "nav.readThisPageIn": "Read this page in",
  "nav.edition": "Edition",
  "nav.chooseEdition": "Choose edition",

  // ------------------------------------------------------------- article
  "article.topics": "Topics",
  "article.share": "Share",
  "article.shareThisArticle": "Share this article",
  "article.save": "Save",
  "article.saved": "Saved",
  "article.viewBio": "View bio",
  "article.by": "By",
  "article.published": "Published",
  "article.updated": "Updated",
  "article.minRead": "{n} min read",
  "article.relatedReading": "Related reading",
  "article.moreFrom": "More from {category}",
  "article.followThisStory": "Follow this story",
  "article.readMore": "Read more",
  "article.inThisArticle": "In this article",
  "article.companies": "Companies",
  "article.people": "People",
  "article.source": "Source",
  "article.correction": "Corrections",

  // -------------------------------------------------------------- lists
  "list.latest": "Latest",
  "list.topStory": "Top story",
  "list.sidebar": "Sidebar",
  "common.advertisement": "Advertisement",
  "common.viewAll": "View all",
  "common.all": "All",
  "common.subscribing": "Subscribing…",
  "common.supportJournalism": "Support independent journalism",
  "common.adBlocker": "Consider disabling your ad blocker for {site}",
  "newsletter.unsubscribeAnytime": "You can unsubscribe at any time. Read our",
  "search.placeholder": "Search articles, jobs, companies, people, events…",
  "search.noResults": "Try different keywords, or browse the categories",
  "search.quickLinks": "Quick links",
  "common.closeAd": "Close ad",
  "list.latestNews": "Latest News",
  "list.featuredCompanies": "Featured Companies",
  "list.featured": "Featured",
  "list.trending": "Trending",
  "list.mostRead": "Most read",
  "list.editorPicks": "Editor's picks",
  "list.loadMore": "Load more",
  "list.showingOf": "Showing {shown} of {total}",
  "list.noResults": "Nothing here yet",
  "list.page": "Page",
  "list.next": "Next",
  "list.previous": "Previous",

  // --------------------------------------------------------- newsletter
  "newsletter.subscribe": "Subscribe",
  "newsletter.emailPlaceholder": "Your email address",
  "newsletter.thanks": "You're subscribed.",
  "newsletter.error": "That didn't go through. Try again.",
  "newsletter.enterEmail": "Enter your email",
  "newsletter.stayUpdated": "Stay updated",
  "newsletter.confirmInbox": "Thanks for subscribing. Check your inbox to confirm.",
  "newsletter.confirmEmail": "Subscribed. Check your email to confirm.",
  "newsletter.needEmail": "Please enter your email address",
  "newsletter.selectLists": "Choose newsletters",
  "newsletter.consent": "By subscribing, you agree to our Privacy Policy.",
  "newsletter.dailyDescription": "The industrial stories that matter, every morning",
  "newsletter.projectsWeekly": "Projects Weekly",
  "newsletter.projectsDescription": "Major project awards and tenders",
  "newsletter.jobAlerts": "Job Alerts",
  "newsletter.jobsDescription": "New roles across the industry",
  "newsletter.eventUpdates": "Event Updates",
  "newsletter.eventsDescription": "Industry events coming up",

  // ------------------------------------------------------------- footer
  "footer.sections": "Sections",
  "footer.company": "Company",
  "footer.about": "About",
  "footer.contact": "Contact",
  "footer.advertise": "Advertise",
  "footer.privacy": "Privacy policy",
  "footer.terms": "Terms of use",
  "footer.rss": "RSS",
  "footer.allRightsReserved": "All rights reserved",
  "footer.followUs": "Follow us",


  // ------------------------------------------------- primary navigation
  // The header and footer link labels. These were hardcoded English arrays
  // until the archive went bilingual, which is why an Arabic page still had
  // an English masthead and an English footer under a translated article.
  "nav.news": "News",
  "nav.latest": "Latest",
  "nav.companies": "Companies",
  "nav.people": "People",
  "nav.events": "Events",
  "nav.jobs": "Jobs",
  "nav.newsletter": "Newsletter",
  "nav.directory": "Directory",
  "nav.industry": "Industry",
  "nav.explore": "Explore",
  "nav.me": "Me",

  // --------------------------------------------------------- categories
  // The industrial taxonomy, as it appears in navigation and on category
  // pages. Category names in the database stay English; these are what a
  // reader sees.
  "cat.construction": "Construction",
  "cat.infrastructure": "Infrastructure",
  "cat.energy": "Energy",
  "cat.manufacturing": "Manufacturing",
  "cat.logistics": "Logistics",
  "cat.real-estate": "Real Estate",
  "cat.transportation": "Transportation",
  "cat.industrial-technology": "Industrial Technology",
  "cat.mining": "Mining",
  "cat.utilities": "Utilities",

  // -------------------------------------------------------- footer links
  "footer.categories": "Categories",
  "footer.editorial": "Editorial",
  "footer.publication": "Publication",
  "footer.aboutUs": "About",
  "footer.contactUs": "Contact Us",
  "footer.termsOfService": "Terms of Service",
  "footer.privacyPolicy": "Privacy Policy",
  "footer.sitemap": "Sitemap",
  "footer.email": "Email",

  // -------------------------------------------------------------- state
  "state.loading": "Loading…",
  "state.error": "Something went wrong.",
  "state.retry": "Try again",
  "state.notFound": "Page not found",
  "state.notFoundBody": "The page you asked for does not exist or has moved.",
  "state.backHome": "Back to the front page",

  // ------------------------------------------------------------ generic
  "common.readingIn": "Reading in {language}",
  "common.translated": "Translated",
  "common.originalEnglish": "Read the original in English",

  // ------------------------------------- directories, filters, events
  // Everything the public pages beyond the homepage put around the
  // content: empty states, filter controls, directory headings, and the
  // events surface, which had the most English of any page.
  "article.companiesInArticle": "Companies in this article",
  "article.mentionedIn": "Mentioned in this article",
  "article.relatedArticles": "Related articles",
  "common.adSpace": "Ad space",
  "common.articles": "Articles",
  "common.cities": "Cities",
  "common.follow": "Follow",
  "common.showLess": "Show less",
  "common.showMore": "Show more",
  "common.viewDetails": "View details",
  "company.keyPeople": "Key people",
  "company.recentNews": "Recent news",
  "company.website": "Website",
  "directory.companies": "Company directory",
  "directory.companiesSubtitle": "The companies building the region",
  "directory.people": "People directory",
  "directory.peopleSubtitle": "Executives, engineers and leaders",
  "directory.peopleTagline": "The people running the region's industry",
  "directory.searchCompanies": "Search companies…",
  "directory.searchPeople": "Search people…",
  "events.connectPeople": "Connect people.",
  "events.coverage": "Event coverage",
  "events.discover": "Discover events.",
  "events.getTickets": "Get tickets",
  "events.happeningNow": "Happening right now",
  "events.hosting": "Hosting an event?",
  "events.listed": "Events listed",
  "events.liveNow": "Live now",
  "events.mostAnticipated": "Most anticipated",
  "events.pastPrompt": "Looking for something that already happened?",
  "events.search": "Search events",
  "events.searchLong": "Search events, topics or locations",
  "events.shapeThe": "Shape the",
  "events.submit": "Submit an event",
  "events.submitYours": "Submit your event",
  "events.tagline": "Every conference, summit and demo day that matters.",
  "events.type": "Event type",
  "events.view": "View event",
  "events.viewAll": "View all events",
  "events.viewPast": "View past events",
  "events.watchLive": "Watch live",
  "filter.allSectors": "All sectors",
  "filter.anyCity": "Any city",
  "filter.bySector": "Filter by sector",
  "filter.clear": "Clear",
  "filter.clearAll": "Clear all filters",
  "filter.clearFilters": "Clear filters",
  "list.browseCategories": "Browse categories",
  "list.browseTags": "Browse tags",
  "list.moreFromNewsroom": "More from the newsroom",
  "list.popularTags": "Popular tags",
  "list.showing": "Showing",
  "list.spotlight": "Spotlight",
  "state.articleNotFound": "Article not found",
  "state.authorNotFound": "Author not found",
  "state.backToNews": "Back to news",
  "state.categoryNotFound": "Category not found",
  "state.errorCompanies": "Could not load companies",
  "state.movedOrDeleted": "It may have been moved or deleted.",
  "state.noArticlesCategory": "No articles in this category yet.",
  "state.noArticlesTag": "No articles with this tag yet.",
  "state.noArticlesYet": "No articles published yet.",
  "state.noCities": "No cities found.",
  "state.noCompanies": "No companies found",
  "state.noPeople": "No people found",
  "state.noResults": "No results found",
  "state.noUpcomingEvents": "No upcoming events on the calendar yet",
  "state.noUpcomingEventsShort": "No upcoming events scheduled yet.",
  "state.tagNotFound": "Tag not found",
  "state.tryAdjusting": "Try adjusting your search or filters",
  // TEMP VERIFY BATCH7
  "about.accuracy": "Accuracy",
  "about.accuracyBody": "We verify reporting before publication, and contract values, project scopes and timelines are checked against primary sources wherever possible. When we get something wrong, we correct it promptly and say so \u2014 accuracy is the basis of any claim to be a publication of record.",
  "about.advertiseWithUs": "Advertise With Us",
  "about.anonymousSources": "Use of Anonymous Sources",
  "about.anonymousSources1": "We prefer named, on-the-record sources. We will grant anonymity only when (a) the information is materially in the public interest, (b) the source has direct knowledge, and (c) the source would face professional or personal harm by being named.",
  "about.anonymousSources2": "When we use an anonymous source, the reporter and at least one editor verify the source's identity and assess their motivation. We describe the source's relationship to the story with as much specificity as anonymity allows.",
  "about.contactForm": "contact form",
  "about.correctionsBody": "We correct factual errors promptly and transparently. When a story is updated to fix a mistake, we add a clearly labelled correction note at the bottom of the article describing what was wrong and what we changed. Substantive corrections are also flagged at the top of the story.",
  "about.correctionsPolicy": "Corrections Policy",
  "about.correctionsResponse": "We aim to respond to all correction requests within one business day.",
  "about.cover1": "We report on contract awards, tenders and project milestones across construction and infrastructure; upstream, midstream and downstream developments in oil & gas; power generation, transmission and renewables; and the manufacturing, logistics, transportation and mining activity that underpins regional economies. We also track the real estate developments, data centers and industrial technology reshaping how these sectors operate.",
  "about.cover2": "Alongside daily news, we maintain structured coverage of the companies active in these markets \u2014 contractors, developers, operators, suppliers and financiers \u2014 and the executives and engineers who lead them. Our project coverage follows major programs from announcement through award, construction and delivery.",
  "about.cover3": "We round this out with listings of industry events and conferences across the region, and job openings from the sectors we cover \u2014 so that {site} serves as a working reference for the industry, not just a news feed.",
  "about.depth": "Depth",
  "about.depthBody": "We do not just report what happened \u2014 we explain what it means for the market. Our readers are professionals who deserve context: how a contract fits a program, how a policy changes a sector's economics, how an appointment signals a company's direction.",
  "about.diversity": "Diversity & Representation",
  "about.diversity1": "The industrial economy is built by people from every country, background, and discipline. Our reporting aims to reflect that \u2014 in the sources we quote, the leaders we profile, and the stories we pursue beyond the region's largest hubs and best-known companies.",
  "about.diversity2": "Our editorial hiring is open to qualified candidates regardless of nationality, gender, religion, or background.",
  "about.editorialIntro": "These are the standards every member of the {site} editorial team is expected to uphold. They govern how we source, verify, write, and correct every story we publish.",
  "about.editorialPolicy": "Editorial Policy & Ethics",
  "about.events1": "{site} maintains a calendar of the conferences, exhibitions and industry gatherings that matter to the sectors we cover \u2014 from energy and construction summits in Riyadh and the GCC to logistics, mining and manufacturing events across MENA and beyond.",
  "about.events2": "Where our team attends or covers an event, that coverage follows the same editorial standards as the rest of the publication. Event organizers can reach us via the",
  "about.factChecking": "Verification & Fact-Checking",
  "about.factChecking1": "Every story published on {site} is checked against primary sources before it goes live. For contract awards and project announcements we rely on official statements, tender documents, regulatory filings or confirmation from the parties involved. For market data we cite the original report. For quotes we retain the original audio or written record.",
  "about.factChecking2": "Senior editors review investigative pieces and any story that names individuals in a critical context. Where a claim cannot be verified to our standard, we either delay publication, attribute it to a single named source, or omit it.",
  "about.fairness": "Fairness",
  "about.fairnessBody": "We give the subjects of our reporting a fair opportunity to respond. We present multiple perspectives on contested issues, distinguish clearly between news and analysis, and apply the same standard of rigor to every company we cover, regardless of its size or commercial relationship with us.",
  "about.getInTouch": "Get in Touch",
  "about.getInTouchBody": "Have a story tip, a correction, a partnership inquiry, or feedback about our coverage? Visit our contact page or reach out directly by email.",
  "about.independence": "Independence",
  "about.independenceBody": "Editorial decisions are made independently of our business relationships. Advertising and sponsorship never determine what we cover or how we cover it. Sponsored and branded content is always clearly labelled and produced separately from news coverage.",
  "about.intro1": "{site} covers the physical economy \u2014 the industries that design, build, power, move and maintain the world around us. Our reporting spans construction, infrastructure, energy, oil & gas, utilities, manufacturing, logistics, transportation, aviation, ports, rail, mining, metals, chemicals, real estate development, data centers and industrial technology.",
  "about.intro2": "Our coverage starts in Saudi Arabia, extends across the GCC and the wider MENA region, and follows the projects, companies and capital flows that connect those markets to the rest of the world. That priority order \u2014 Saudi Arabia, then the GCC, then MENA, then global \u2014 shapes what we cover first and in what depth.",
  "about.intro3": "{site} is written for the people who work in these industries: contractors, developers, engineers, operators, procurement teams, financiers and policymakers. We assume our readers know their sectors, and we aim to tell them something they can use.",
  "about.mission": "Our Mission",
  "about.mission1": "The industrial economy is reported in fragments \u2014 a contract award here, an executive appointment there, a project milestone buried in a quarterly filing. {site} exists to bring that reporting together into structured, connected coverage: news, the companies behind it, the people who lead them, the projects they deliver, the events where the industry meets, and the jobs it creates.",
  "about.mission2": "When we report on a project, we link it to the owners, contractors and consultants delivering it. When we cover an appointment, we connect it to the company's track record. The goal is a body of coverage that compounds \u2014 where each story adds context to the ones around it.",
  "about.mission3": "Our editorial decisions are driven by what matters to people working in these sectors, not by press-release volume or publicity cycles. We would rather publish one story that changes how a reader understands a market than ten that restate an announcement.",
  "about.orUseOur": "or use our",
  "about.ownership": "Ownership & Funding",
  "about.ownership1": "{site} is operated by {legalName}. The publication is funded by advertising, sponsorship, and partnership revenue. No advertiser, sponsor, or partner has any role in editorial decisions or pre-publication review of stories.",
  "about.ownership2": "When a story involves a company that is also a commercial partner of {site}, we disclose the relationship in the article.",
  "about.spottedError": "Spotted an error? Email",
  "about.title": "About {site}",
  "about.whatWeCover": "What We Cover",
  "advertise.adFormats": "Ad Formats",
  "advertise.adsSponsorships": "{site} Ads & Sponsorships",
  "advertise.allInquiriesSentTo": "All inquiries are sent to",
  "advertise.budget10to25k": "Yes, $10,000\u2013$25,000",
  "advertise.budget25to50k": "Yes, $25,000\u2013$50,000",
  "advertise.budget50kPlus": "Yes, $50,000+",
  "advertise.budgetNone": "No / I'm looking for editorial coverage",
  "advertise.budgetQuestion": "Do you have a marketing budget for this initiative?",
  "advertise.budgetUnder10k": "Yes, less than $10,000",
  "advertise.companyPlaceholder": "Your company",
  "advertise.contactPageLink": "contact page",
  "advertise.emailPlaceholder": "your@company.com",
  "advertise.formNote": "This form is for paid sponsorship and advertising inquiries only. For editorial pitches or press outreach, please see our",
  "advertise.inContent": "In-Content",
  "advertise.inContentDesc": "728\u00d790 units placed within article bodies, seen at the point of reading.",
  "advertise.indChemicals": "Chemicals",
  "advertise.indConstruction": "Construction & Contracting",
  "advertise.indDataCenters": "Data Centers / Industrial Technology",
  "advertise.indEnergy": "Energy / Oil & Gas",
  "advertise.indEngineering": "Engineering / Professional Services",
  "advertise.indFinancial": "Financial Services",
  "advertise.indGovernment": "Government / Public Sector",
  "advertise.indLogistics": "Logistics / Supply Chain",
  "advertise.indMining": "Mining & Metals",
  "advertise.indRealEstate": "Real Estate Development",
  "advertise.indTransport": "Transportation / Aviation / Ports / Rail",
  "advertise.indUtilities": "Utilities & Power",
  "advertise.inquiryReceived": "Inquiry received",
  "advertise.inquiryReceivedBody": "Our media team will reach out within 1 business day.",
  "advertise.intro": "{site} is read by the people who plan, build, and operate the physical economy \u2014 contractors, developers, engineers, energy and utility executives, logistics operators, procurement leaders, and the financiers behind them \u2014 with coverage focused on Saudi Arabia, the GCC and MENA. Advertising with {site} puts your brand alongside the news these decision-makers rely on, in a professional editorial environment rather than a general-interest feed.",
  "advertise.leaderboard": "Leaderboard",
  "advertise.leaderboardDesc": "970\u00d7250 and 970\u00d790 placements at the top of the homepage, section fronts, and articles.",
  "advertise.mediaKit": "For a media kit, current availability, and rates, email",
  "advertise.messageHint": "This is your opportunity to ask us for specifics to be addressed in our initial reply. Please keep this section short and to the point about your ask.",
  "advertise.messagePlaceholder": "Tell us about your advertising goals...",
  "advertise.mobile": "Mobile",
  "advertise.mobileDesc": "Mobile-optimized banner and sticky formats for readers on phones and tablets.",
  "advertise.native": "Native & Branded Content",
  "advertise.nativeDesc": "Clearly labelled sponsored articles and branded features, produced to editorial standards.",
  "advertise.newsletterSponsorship": "Newsletter Sponsorship",
  "advertise.newsletterSponsorshipDesc": "Dedicated placements in {name}, delivered to subscribers' inboxes every morning.",
  "advertise.objBranded": "Distribute branded content / sponsored article",
  "advertise.objDisplay": "Run display advertising on the site",
  "advertise.objNewsletter": "Sponsor the newsletter",
  "advertise.objOther": "Something else (please explain in the Message area)",
  "advertise.objPromote": "Promote an event, tender, or recruitment campaign",
  "advertise.objectives": "Advertising Objectives",
  "advertise.orUseForm": "or use the form below.",
  "advertise.rightRail": "Right Rail",
  "advertise.rightRailDesc": "300\u00d7250 and 300\u00d7600 units in the sidebar, persistent across article and listing pages.",
  "advertise.rolePlaceholder": "Your role",
  "advertise.submitFailed": "Couldn't submit your inquiry",
  "advertise.title": "Advertise with {site}",
  "common.lastUpdated": "Last updated",
  "common.other": "Other",
  "contact.advertising": "Advertising & Sponsorships",
  "contact.advertisingBody": "For advertising and sponsorship inquiries, please",
  "contact.advertisingLink": "visit our advertise page",
  "contact.advertisingSuffix": "and our media team will get back to you quickly.",
  "contact.companyPlaceholder": "Your company or organization",
  "contact.corrections": "Corrections & Feedback",
  "contact.correctionsBody": "We take accuracy seriously. If you've spotted an error in our reporting or have feedback about our coverage, please reach out to",
  "contact.emailPlaceholder": "your@email.com",
  "contact.enquiryAbout": "What is your enquiry about?",
  "contact.eventsListings": "Events & Listings",
  "contact.eventsListingsBody": "Organizing an industry event, or want a role or event listed on the site? Please contact",
  "contact.intro": "Whether you have a news tip, want to work with us, or just have a question \u2014 we're here to help. Choose the most relevant category below or use the general inquiry form.",
  "contact.messagePlaceholder": "Tell us more about your inquiry...",
  "contact.messageSent": "Message sent",
  "contact.messageSentBody": "We've received your message and will reply within 1 business day.",
  "contact.newsTips": "News Tips",
  "contact.newsTipsBody": "Know about a contract award, project development, or industry move we should be covering? We'd love to hear from you. Please drop us a note at",
  "contact.newsTipsNote": "If you prefer to remain anonymous, please mention that in your email and we will protect your identity.",
  "contact.otherInquiries": "Other Inquiries",
  "contact.otherInquiriesBody": "For anything else, fill out the form below and we'll route your message to the right team. All inquiries are sent to",
  "contact.partnership": "Partnership Inquiry",
  "contact.pressReleases": "Press Releases & Announcements",
  "contact.pressReleasesBody": "Announcing a contract win, project milestone, executive appointment, or product for the industrial sector? Send your release to",
  "contact.pressReleasesNote": "Please include the key facts \u2014 parties involved, scope, value if disclosed, and timeline \u2014 plus any supporting materials.",
  "contact.sendFailed": "Couldn't send your message",
  "contact.workEmailNote": "If you're able, we prefer to connect through your work email.",
  "explore.companiesDesc": "Contractors, operators & manufacturers",
  "explore.content": "Content",
  "explore.discover": "Discover",
  "explore.ecosystem": "Ecosystem",
  "explore.eventsDesc": "Conferences & meetups",
  "explore.jobsDesc": "Tech career opportunities",
  "explore.newsDesc": "Latest tech news",
  "form.companyName": "Company Name",
  "form.completeRequired": "Please complete all required fields",
  "form.email": "Email",
  "form.firstName": "First Name",
  "form.firstNamePlaceholder": "First name",
  "form.industry": "Industry",
  "form.jobTitle": "Job Title",
  "form.lastName": "Last Name",
  "form.lastNamePlaceholder": "Last name",
  "form.message": "Message",
  "form.pleaseSelect": "Please Select",
  "form.sending": "Sending\u2026",
  "form.submit": "Submit",
  "legal.placeholderNotice": "Placeholder \u2014 to be reviewed by legal counsel",
  "legal.reviewRequired": "This is placeholder content. Final legal review required before public launch.",
  "legal.reviewRequiredBody": "Nothing on this page is legal advice. Each section is a working draft and will be replaced with counsel-reviewed text prior to launch.",
  "newsletter.alreadySubscribed": "Already subscribed",
  "newsletter.alreadySubscribedBody": "We've got you. Check your inbox for our most recent issue.",
  "newsletter.asPosted": "As posted",
  "newsletter.byOurNewsroom": "Written by our newsroom",
  "newsletter.energyBrief": "Energy Brief",
  "newsletter.energyDetail": "Oil & gas, power, utilities and renewables: upstream developments, offtake deals, and the policy moves shaping regional energy.",
  "newsletter.eventsDetail": "Upcoming conferences, exhibitions, and industry gatherings across Saudi Arabia, the GCC, and MENA.",
  "newsletter.everyMorning": "Every morning",
  "newsletter.failed": "Subscription failed",
  "newsletter.freeToRead": "Free to read",
  "newsletter.heroBody": "Contract awards, project milestones, energy moves, and the people behind them \u2014 in one concise read.",
  "newsletter.heroTitle": "The Industrial Economy, Every Morning",
  "newsletter.jobsDetail": "New roles across the industries we cover \u2014 engineering, construction, energy, logistics, and operations.",
  "newsletter.monthly": "Monthly",
  "newsletter.morningBriefing": "Your morning briefing",
  "newsletter.noSpam": "No spam, ever",
  "newsletter.preferencesSaved": "Preferences saved",
  "newsletter.preferencesSavedBody": "You'll receive {n} newsletter(s). Enter your email above to subscribe.",
  "newsletter.projectsDetail": "Major project awards, tenders, and milestones across construction and infrastructure \u2014 tracked from announcement to delivery.",
  "newsletter.sampleEnergy": "Energy: capacity additions and offtake agreements",
  "newsletter.sampleEnergySub": "Power, oil & gas, and renewables in brief",
  "newsletter.sampleHeadline": "Main contract awarded on a giga-project package",
  "newsletter.sampleIntro": "A sample of how {name} lands in your inbox",
  "newsletter.sampleLede": "The day's most consequential story, with the parties, scope, and what it signals for the wider program...",
  "newsletter.samplePeople": "People: appointments across the sector",
  "newsletter.samplePeopleSub": "Who's moving where, and why it matters",
  "newsletter.selectListsBody": "Select the briefings that match your work. You can update your preferences anytime.",
  "newsletter.subscribeToCount": "Subscribe to {n} newsletters",
  "newsletter.unsubscribeAnytimeShort": "Unsubscribe anytime",
  "newsletter.weekly": "Weekly",
  "newsletter.whatToExpect": "What to Expect",
  "newsletter.youreIn": "You're in",
  "newsletter.youreInBody": "Welcome email on its way. Check your inbox in a minute.",
  "privacy.children1": "The Service is not directed to children under the age required by law in your jurisdiction. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, contact us so we can remove it.",
  "privacy.childrenTitle": "8. Children's Privacy",
  "privacy.collectAccount": "name, email, password hash, and basic profile fields you provide if you register for an account.",
  "privacy.collectAccountLabel": "Account information:",
  "privacy.collectForms": "information you send us through our contact and advertising inquiry forms, such as your name, email, company, and message.",
  "privacy.collectFormsLabel": "Form submissions:",
  "privacy.collectIntro": "We collect the following categories of information:",
  "privacy.collectNewsletter": "your email address, the newsletters you select, and your consent preferences.",
  "privacy.collectNewsletterLabel": "Newsletter subscription details:",
  "privacy.collectTitle": "1. Information We Collect",
  "privacy.collectUsage": "device and browser information, pages visited, and similar analytics data collected through cookies and comparable technologies.",
  "privacy.collectUsageLabel": "Usage data:",
  "privacy.contact1": "Privacy questions, requests, or complaints can be sent to",
  "privacy.contactTitle": "9. Contact",
  "privacy.cookiePreferences": "cookie preferences",
  "privacy.cookies1": "We use cookies and similar technologies for essential functionality, analytics, and (where you opt in) advertising and marketing. You can revisit your choices at any time via",
  "privacy.cookiesTitle": "6. Cookies",
  "privacy.lead": "This Privacy Policy explains how {legalName} (\u201c{site}\u201d) collects, uses, and shares information when you use {domain} and the services we provide through it (the \u201cService\u201d). It applies to readers, newsletter subscribers, and visitors. Your use of the Service is also governed by our",
  "privacy.retention1": "We retain personal data for as long as your account or subscription is active or as needed to provide the Service. After account closure or unsubscription, we delete or anonymize data within a reasonable period, except where retention is required by law.",
  "privacy.retentionTitle": "4. Data Retention",
  "privacy.rightAccess": "Access",
  "privacy.rightAccessBody": "request a copy of the personal data we hold about you.",
  "privacy.rightErasure": "Erasure",
  "privacy.rightErasureBody": "ask us to delete your account, subscription, and associated data.",
  "privacy.rightPortability": "Portability",
  "privacy.rightPortabilityBody": "receive your data in a machine-readable format.",
  "privacy.rightRectification": "Rectification",
  "privacy.rightRectificationBody": "correct inaccurate data via your account or by contacting us.",
  "privacy.rightsContact": "To exercise any of these rights, contact us at",
  "privacy.rightsIntro": "Depending on your jurisdiction you may have the following rights:",
  "privacy.rightsTitle": "5. Your Rights",
  "privacy.rightsUnsubscribe": "You can unsubscribe from any newsletter at any time using the link in the email footer.",
  "privacy.sharing1": "We share information with service providers who help us run the Service \u2014 for example, email delivery, hosting and infrastructure, and analytics vendors. These providers process data on our behalf and are not permitted to use it for their own purposes.",
  "privacy.sharing2": "We do not sell personal information. A finalized list of sub-processors with contractual commitments will be published prior to launch.",
  "privacy.sharingTitle": "3. Data Sharing",
  "privacy.transfers1": "Our readers, and the service providers we rely on, are located in multiple countries. Personal data may therefore be processed outside the country in which you live. Where personal data is transferred between jurisdictions, we rely on appropriate safeguards such as standard contractual clauses or equivalent mechanisms recognized under applicable law.",
  "privacy.transfersTitle": "7. International Transfers",
  "privacy.updates1": "We may update this Privacy Policy from time to time. Material changes will be announced on this page and, where appropriate, through additional notice. The \u201cLast updated\u201d date above will always reflect the most recent revision.",
  "privacy.updatesTitle": "10. Updates to this Policy",
  "privacy.useAdvertising": "Serve and measure advertising on the site, consistent with your cookie choices.",
  "privacy.useCommunicate": "Communicate with you about your account and the Service.",
  "privacy.useDeliver": "Deliver the newsletters and briefings you subscribe to.",
  "privacy.useIntro": "We use the information we collect to:",
  "privacy.useOperate": "Operate, secure, and improve the Service, including understanding which coverage our readers find useful.",
  "privacy.useRespond": "Respond to your inquiries, tips, and feedback.",
  "privacy.useTitle": "2. How We Use Information",
  "search.minCharacters": "Enter at least 2 characters to search across all content",
  "search.newsCompaniesPeople": "Search news, companies, people...",
  "search.nothingMatching": "We couldn't find anything matching \"{query}\". Try different keywords.",
  "search.recent": "Recent",
  "search.resultsFor": "{count} results for \"{query}\"",
  "search.searching": "Searching...",
  "search.trendingTopics": "Trending Topics",
  "sitemap.aboutDesc": "Learn about {site}",
  "sitemap.advertiseDesc": "Advertising opportunities",
  "sitemap.authorPages": "Author Pages",
  "sitemap.companyProfiles": "Company Profiles",
  "sitemap.contactDesc": "Get in touch with us",
  "sitemap.dashboardDesc": "Your personalized dashboard",
  "sitemap.dynamicPages": "Dynamic Pages",
  "sitemap.dynamicPagesIntro": "In addition to the pages listed above, {site} has dynamic content pages including:",
  "sitemap.eventDetails": "Event Details",
  "sitemap.eventsDesc": "Upcoming tech events",
  "sitemap.intro": "A complete overview of all pages and sections on {site}.",
  "sitemap.jobDetails": "Job Details",
  "sitemap.jobsDesc": "Browse tech job opportunities",
  "sitemap.legal": "Legal",
  "sitemap.mainPages": "Main Pages",
  "sitemap.newsHomepage": "News Homepage",
  "sitemap.newsHomepageDesc": "Latest industry news and updates",
  "sitemap.newsletterDesc": "Subscribe to our newsletter",
  "sitemap.peopleDesc": "Connect with tech professionals",
  "sitemap.peopleProfiles": "People Profiles",
  "sitemap.privacyDesc": "How we handle your data",
  "sitemap.profileDesc": "Manage your profile settings",
  "sitemap.termsDesc": "Terms and conditions",
  "state.tryAgainMoment": "Try again in a moment.",
  "terms.acceptableUse1": "You agree not to misuse the Service. Examples of prohibited activity include scraping or republishing our content without permission, posting unlawful or infringing content, harassing other users, attempting to gain unauthorized access, or interfering with the Service's operation.",
  "terms.acceptableUseTitle": "4. Acceptable Use",
  "terms.acceptance1": "By accessing {domain} or otherwise using the services provided by {legalName} (the \u201cService\u201d), you agree to be bound by these Terms of Service and any policies referenced here. If you do not agree, you must not use the Service.",
  "terms.acceptanceTitle": "1. Acceptance of Terms",
  "terms.accounts1": "Some features may require an account or newsletter subscription. You are responsible for the accuracy of the information you provide and for keeping your credentials secure. You must notify us promptly of any unauthorized access to your account.",
  "terms.accountsTitle": "3. User Accounts",
  "terms.changes1": "We may update these Terms from time to time. We will post the updated version on this page and, where appropriate, notify you. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.",
  "terms.changesTitle": "12. Changes to Terms",
  "terms.contact1": "Questions about these Terms can be sent to",
  "terms.contactTitle": "13. Contact",
  "terms.description1": "{site} is an online publication covering the industrial economy \u2014 construction, infrastructure, energy, manufacturing, logistics, and related sectors. The Service includes news and analysis, company and people coverage, project tracking, event listings, job listings, and email newsletters. Features may change over time as the Service evolves.",
  "terms.descriptionTitle": "2. Description of Service",
  "terms.disclaimers1": "The Service is provided \u201cas is\u201d without warranties of any kind, express or implied, to the maximum extent permitted by applicable law.",
  "terms.disclaimersTitle": "8. Disclaimers",
  "terms.editorial1": "Content published on the Service is provided for general information only. It does not constitute professional, financial, investment, or legal advice, and should not be relied upon as the basis for any commercial decision. Sponsored and branded content is clearly labelled as such.",
  "terms.editorialTitle": "6. Editorial Content",
  "terms.governingLaw1": "These Terms are governed by applicable law in the jurisdiction in which {legalName} is established, without regard to conflict of law principles. Specific venue and jurisdiction will be confirmed in the final version of these Terms.",
  "terms.governingLawTitle": "11. Governing Law",
  "terms.ip1": "{legalName} and its licensors retain all rights in the Service, including its software, branding, and editorial content. You retain ownership of content you submit, and grant {legalName} a license to host, process, and display it for the purpose of providing the Service.",
  "terms.ipTitle": "5. Intellectual Property",
  "terms.lead": "These Terms of Service govern your access to and use of {site}, operated by {legalName}. Please read them carefully.",
  "terms.liability1": "To the fullest extent permitted by law, {legalName} will not be liable for indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Service.",
  "terms.liabilityTitle": "9. Limitation of Liability",
  "terms.privacy1": "Your use of the Service is also governed by our",
  "terms.privacy2": ", which explains how we collect, use, and share information.",
  "terms.privacyTitle": "7. Privacy",
  "terms.termination1": "We may suspend or terminate your access to the Service if you violate these Terms or if continued provision of the Service is not reasonably practical. You may close your account or unsubscribe from our newsletters at any time.",
  "terms.terminationTitle": "10. Termination",
  "time.daysAgo": "{n}d ago",
  "time.hoursAgo": "{n}h ago",
  "time.justNow": "Just now",
} as const;

export type UiKey = keyof typeof UI_STRINGS;

/**
 * Fill {placeholders}. Kept deliberately dumb — no plural rules, no dates.
 * Arabic pluralisation has six forms and getting it half-right is worse than
 * not attempting it, so anything genuinely plural-sensitive gets its own key
 * rather than a rule engine.
 */
export function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (m, k) =>
    vars[k] === undefined ? m : String(vars[k]),
  );
}
