CREATE TABLE IF NOT EXISTS `accelerators` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`shortDescription` text,
	`logo` text,
	`website` text,
	`location` varchar(255),
	`regionId` int,
	`sectorId` int,
	`programLength` varchar(100),
	`equity` varchar(100),
	`funding` varchar(100),
	`applicationDeadline` timestamp,
	`programStartDate` timestamp,
	`programEndDate` timestamp,
	`benefits` text,
	`requirements` text,
	`applicationUrl` text,
	`status` enum('active','upcoming','completed','paused') DEFAULT 'active',
	`isFeatured` boolean DEFAULT false,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accelerators_id` PRIMARY KEY(`id`),
	CONSTRAINT `accelerators_slug_unique` UNIQUE(`slug`)
);
